export interface RoadmapProblem {
  id: string;
  titleEn: string;
  titleBn: string;
  difficulty: "EASY" | "MEDIUM" | "HARD" | "INSANE";
  url: string;
  solutionUrl?: string;
  isCompleted?: boolean;
  isStarred?: boolean;
}

export interface RoadmapPrereq {
  id: string;
  titleEn: string;
  titleBn: string;
  subtitleEn: string;
  subtitleBn: string;
  url: string;
}

export interface RoadmapNode {
  id: string;
  labelEn: string;
  labelBn: string;
  x: number;
  y: number;
  width?: number;
  height?: number;
  icon?: string;
  category: string;
  badge?: string;
  prerequisites: RoadmapPrereq[];
  children: string[]; // target node IDs
  problems: RoadmapProblem[];
}

export interface RoadmapTrack {
  id: string;
  titleEn: string;
  titleBn: string;
  descriptionEn: string;
  descriptionBn: string;
  icon: string;
  canvasWidth: number;
  canvasHeight: number;
  nodes: RoadmapNode[];
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. BD Software Engineering Career Roadmap (12 Core Subjects)
// ─────────────────────────────────────────────────────────────────────────────
export const BD_SWE_ROADMAP: RoadmapTrack = {
  id: "bd-swe",
  titleEn: "BD Software Engineering Career",
  titleBn: "বাংলাদেশ সফটওয়্যার ক্যারিয়ার রোডম্যাপ",
  descriptionEn: "Complete 12-subject path for Bangladesh tech interviews from C# syntax to System Design.",
  descriptionBn: "C# ভাষার শুরু থেকে সিস্টেম ডিজাইন পর্যন্ত ১২টি মূল বিষয়ের পূর্ণাঙ্গ প্রস্তুতি রোডম্যাপ।",
  icon: "Briefcase",
  canvasWidth: 1000,
  canvasHeight: 900,
  nodes: [
    {
      id: "csharp",
      labelEn: "Programming in C#",
      labelBn: "C# প্রোগ্রামিং",
      x: 390,
      y: 40,
      width: 190,
      height: 52,
      category: "Foundations",
      icon: "Code",
      badge: "Core",
      prerequisites: [],
      children: ["oop", "dsa"],
      problems: [
        { id: "cs-1", titleEn: "C# Variables, Primitives & Memory", titleBn: "C# ভেরিয়েবল ও মেমোরি", difficulty: "EASY", url: "/subjects/csharp/csharp-variables" },
        { id: "cs-2", titleEn: "Control Flow & Pattern Matching", titleBn: "কন্ট্রোল ফ্লো ও প্যাটার্ন ম্যাচিং", difficulty: "EASY", url: "/subjects/csharp/csharp-if-else" },
        { id: "cs-3", titleEn: "Collections: List vs Array vs Dictionary", titleBn: "কালেকশন ও ডেটা সংরক্ষণ", difficulty: "MEDIUM", url: "/subjects/csharp/collections-list" },
        { id: "cs-4", titleEn: "Value vs Reference Types, Boxing/Unboxing", titleBn: "ভ্যালু বনাম রেফারেন্স টাইপ", difficulty: "MEDIUM", url: "/subjects/csharp/types-value-types" },
        { id: "cs-5", titleEn: "Generics & Constraints", titleBn: "জেনেরিক্স ও শর্তাবলি", difficulty: "MEDIUM", url: "/subjects/csharp/generics-classes" },
        { id: "cs-6", titleEn: "LINQ Operations & Deferred Execution", titleBn: "LINQ কোয়েরি ও ডেফার্ড এক্সিকিউশন", difficulty: "HARD", url: "/subjects/csharp/linq-where" },
        { id: "cs-7", titleEn: "Async/Await, Tasks & Threading", titleBn: "অ্যাসিঙ্ক ও টাস্ক প্যারালেলিজম", difficulty: "HARD", url: "/subjects/csharp/async-await" },
        { id: "cs-8", titleEn: "Garbage Collector & IDisposable Pattern", titleBn: "মেমোরি ম্যানেজমেন্ট ও ডিসপোজ", difficulty: "HARD", url: "/subjects/csharp/resources-using" },
      ],
    },
    {
      id: "git",
      labelEn: "Git & Version Control",
      labelBn: "গিট ও ভার্সন কন্ট্রোল",
      x: 650,
      y: 40,
      width: 180,
      height: 52,
      category: "Foundations",
      icon: "GitBranch",
      prerequisites: [],
      children: ["dotnet"],
      problems: [
        { id: "git-1", titleEn: "Git Fundamentals: Commit, Branch & Merge", titleBn: "গিট বেসিক ও ব্রাঞ্চিং", difficulty: "EASY", url: "/subjects/csharp" },
        { id: "git-2", titleEn: "Merge vs Rebase & Conflict Resolution", titleBn: "মার্জ বনাম রিব্যাস ও কনফ্লিক্ট সমাধান", difficulty: "MEDIUM", url: "/subjects/csharp" },
        { id: "git-3", titleEn: "Git Flow & Pull Request Best Practices", titleBn: "গিট ফ্লো ও পিআর রিভিউ কালচার", difficulty: "MEDIUM", url: "/subjects/csharp" },
      ],
    },
    {
      id: "oop",
      labelEn: "OOP in C#",
      labelBn: "অবজেক্ট ওরিয়েন্টেড ডিজাইন",
      x: 270,
      y: 160,
      width: 180,
      height: 52,
      category: "Core Engineering",
      icon: "Boxes",
      badge: "Crucial",
      prerequisites: [
        { id: "csharp", titleEn: "C# Basics", titleBn: "C# বেসিক", subtitleEn: "Classes and methods", subtitleBn: "ক্লাস ও মেথড", url: "/subjects/csharp" },
      ],
      children: ["dotnet", "design-patterns", "uml"],
      problems: [
        { id: "oop-1", titleEn: "Encapsulation, Abstraction & Access Modifiers", titleBn: "এনক্যাপসুলেশন ও অ্যাবস্ট্রাকশন", difficulty: "EASY", url: "/subjects/oop" },
        { id: "oop-2", titleEn: "Inheritance vs Composition Trade-offs", titleBn: "ইনহেরিটেন্স বনাম কম্পোজিশন", difficulty: "MEDIUM", url: "/subjects/oop" },
        { id: "oop-3", titleEn: "Polymorphism, Virtual Tables & Overriding", titleBn: "পলিমরফিজম ও মেথড ওভাররাইড", difficulty: "MEDIUM", url: "/subjects/oop" },
        { id: "oop-4", titleEn: "SOLID Principles: SRP, OCP, LSP, ISP, DIP", titleBn: "SOLID নীতিমালা গভীর বিশ্লেষণ", difficulty: "HARD", url: "/subjects/oop" },
        { id: "oop-5", titleEn: "Abstract Classes vs Interfaces in Modern .NET", titleBn: "অ্যাবস্ট্রাক্ট ক্লাস বনাম ইন্টারফেস", difficulty: "MEDIUM", url: "/subjects/oop" },
      ],
    },
    {
      id: "dsa",
      labelEn: "Data Structures & Algorithms",
      labelBn: "ডেটা স্ট্রাকচার ও অ্যালগরিদম",
      x: 510,
      y: 160,
      width: 220,
      height: 52,
      category: "Core Engineering",
      icon: "Binary",
      badge: "Essential",
      prerequisites: [
        { id: "csharp", titleEn: "C# Collections", titleBn: "C# কালেকশন", subtitleEn: "Arrays and Lists", subtitleBn: "অ্যারে ও লিস্ট", url: "/subjects/csharp" },
      ],
      children: ["database", "competitive-programming"],
      problems: [
        { id: "dsa-1", titleEn: "Time & Space Asymptotic Complexity", titleBn: "টাইম ও স্পেস কমপ্লেক্সিটি", difficulty: "EASY", url: "/subjects/dsa" },
        { id: "dsa-2", titleEn: "Arrays, Hash Maps & Two Pointers", titleBn: "অ্যারে ও হ্যাশ ম্যাপ কৌশল", difficulty: "EASY", url: "/subjects/dsa" },
        { id: "dsa-3", titleEn: "Binary Trees & BST Traversals (BFS/DFS)", titleBn: "বাইনারি ট্রি ও ট্রাভার্সাল", difficulty: "MEDIUM", url: "/subjects/dsa" },
        { id: "dsa-4", titleEn: "Graph Traversals (BFS, DFS, Dijkstra)", titleBn: "গ্রাফ অ্যালগরিদম ও শর্টেস্ট পাথ", difficulty: "HARD", url: "/subjects/dsa" },
        { id: "dsa-5", titleEn: "Dynamic Programming: Memoization & Tabulation", titleBn: "ডায়নামিক প্রোগ্রামিং কৌশল", difficulty: "HARD", url: "/subjects/dsa" },
      ],
    },
    {
      id: "uml",
      labelEn: "UML Diagrams",
      labelBn: "UML ডায়াগ্রাম",
      x: 770,
      y: 160,
      width: 170,
      height: 52,
      category: "Architecture",
      icon: "PenTool",
      prerequisites: [
        { id: "oop", titleEn: "OOP Principles", titleBn: "OOP নীতিমালা", subtitleEn: "Class relationships", subtitleBn: "ক্লাস সম্পর্ক", url: "/subjects/oop" },
      ],
      children: ["system-design"],
      problems: [
        { id: "uml-1", titleEn: "Class Diagrams & Association/Aggregation", titleBn: "ক্লাস ডায়াগ্রাম সম্পর্ক", difficulty: "EASY", url: "/subjects/uml" },
        { id: "uml-2", titleEn: "Sequence Diagrams for RESTful API Flows", titleBn: "সিকোয়েন্স ডায়াগ্রাম ও এপিআই কল", difficulty: "MEDIUM", url: "/subjects/uml" },
        { id: "uml-3", titleEn: "Activity & State Machine Modeling", titleBn: "স্টেট মেশিন ও অ্যাক্টিভিটি মডেলিং", difficulty: "MEDIUM", url: "/subjects/uml" },
      ],
    },
    {
      id: "dotnet",
      labelEn: ".NET Core / ASP.NET",
      labelBn: ".NET কোর ও ওয়েব এপিআই",
      x: 200,
      y: 290,
      width: 200,
      height: 52,
      category: "Web & Backend",
      icon: "Cpu",
      badge: "Industry Standard",
      prerequisites: [
        { id: "oop", titleEn: "OOP & Interfaces", titleBn: "OOP ও ইন্টারফেস", subtitleEn: "Inversion of Control", subtitleBn: "ডিপেন্ডেন্সি ইনজেকশন", url: "/subjects/oop" },
        { id: "git", titleEn: "Git VCS", titleBn: "গিট ভার্সন কন্ট্রোল", subtitleEn: "Code workflow", subtitleBn: "প্রজেক্ট ব্রাঞ্চিং", url: "/subjects/csharp" },
      ],
      children: ["database", "design-patterns"],
      problems: [
        { id: "net-1", titleEn: "ASP.NET Core Middleware Pipeline & Request Lifecycle", titleBn: "মিডলওয়্যার পাইপলাইন", difficulty: "EASY", url: "/subjects/dotnet" },
        { id: "net-2", titleEn: "Dependency Injection Lifetimes: Transient, Scoped, Singleton", titleBn: "ডিপেন্ডেন্সি ইনজেকশন লাইফটাইম", difficulty: "MEDIUM", url: "/subjects/dotnet" },
        { id: "net-3", titleEn: "Entity Framework Core, Migrations & Linq-to-Entities", titleBn: "ইএফ কোর ও মাইগ্রেশন", difficulty: "MEDIUM", url: "/subjects/dotnet" },
        { id: "net-4", titleEn: "JWT Authentication, Authorization & Claims", titleBn: "জেডব্লিউটি অথেনটিকেশন ও সিকিউরিটি", difficulty: "HARD", url: "/subjects/dotnet" },
        { id: "net-5", titleEn: "Clean Architecture & CQRS with MediatR", titleBn: "ক্লিন আর্কিটেকচার ও CQRS", difficulty: "HARD", url: "/subjects/dotnet" },
      ],
    },
    {
      id: "database",
      labelEn: "Database & PostgreSQL",
      labelBn: "ডেটাবেজ ও PostgreSQL",
      x: 460,
      y: 290,
      width: 200,
      height: 52,
      category: "Persistence",
      icon: "Database",
      badge: "High Demand",
      prerequisites: [
        { id: "dsa", titleEn: "DSA", titleBn: "DSA", subtitleEn: "B-Trees & Hashing", subtitleBn: "ইনডেক্সিং কনসেপ্ট", url: "/subjects/dsa" },
      ],
      children: ["system-design", "networks"],
      problems: [
        { id: "db-1", titleEn: "SQL Joins, Subqueries & Aggregations", titleBn: "SQL জয়েন ও সাবকোয়েরি", difficulty: "EASY", url: "/subjects/database" },
        { id: "db-2", titleEn: "Relational Schema Normalization (1NF to BCNF)", titleBn: "ডেটাবেজ নরমালাইজেশন", difficulty: "MEDIUM", url: "/subjects/database" },
        { id: "db-3", titleEn: "B-Tree Indexes, Hash Indexes & Query Plans (EXPLAIN)", titleBn: "ইনডেক্সিং কৌশল ও কুয়েরি প্ল্যান", difficulty: "HARD", url: "/subjects/database" },
        { id: "db-4", titleEn: "ACID Properties & Transaction Isolation Levels", titleBn: "ট্রানজ্যাকশন ও আইসোলেশন লেভেল", difficulty: "HARD", url: "/subjects/database" },
      ],
    },
    {
      id: "competitive-programming",
      labelEn: "Competitive Programming",
      labelBn: "প্রতিযোগিতামূলক কোডিং",
      x: 720,
      y: 290,
      width: 210,
      height: 52,
      category: "Problem Solving",
      icon: "Trophy",
      prerequisites: [
        { id: "dsa", titleEn: "Data Structures", titleBn: "ডেটা স্ট্রাকচার", subtitleEn: "Standard algorithms", subtitleBn: "স্ট্যান্ডার্ড অ্যালগরিদম", url: "/subjects/dsa" },
      ],
      children: ["ai-ml"],
      problems: [
        { id: "cp-1", titleEn: "Fast I/O & Bitwise Tricks in C++ / C#", titleBn: "ফাস্ট আই/ও ও বিটওয়াইজ ট্রিকস", difficulty: "MEDIUM", url: "/subjects/competitive-programming" },
        { id: "cp-2", titleEn: "Number Theory: Sieve, Modular Arithmetic & GCD", titleBn: "নাম্বার থিওরি ও মডিউলার পাটিগণিত", difficulty: "MEDIUM", url: "/subjects/competitive-programming" },
        { id: "cp-3", titleEn: "Segment Tree & Fenwick Tree Range Queries", titleBn: "সেগমেন্ট ট্রি ও রেঞ্জ কুয়েরি", difficulty: "HARD", url: "/subjects/competitive-programming" },
      ],
    },
    {
      id: "design-patterns",
      labelEn: "Design Patterns",
      labelBn: "ডিজাইন প্যাটার্ন ও প্রিন্সিপালস",
      x: 230,
      y: 430,
      width: 190,
      height: 52,
      category: "Architecture",
      icon: "Layers",
      badge: "Interview Must",
      prerequisites: [
        { id: "oop", titleEn: "OOP & SOLID", titleBn: "OOP ও SOLID", subtitleEn: "Inheritance and DI", subtitleBn: "ডিপেন্ডেন্সি ইনজেকশন", url: "/subjects/oop" },
      ],
      children: ["system-design"],
      problems: [
        { id: "dp-1", titleEn: "Singleton, Factory & Abstract Factory Patterns", titleBn: "সিংগলটন ও ফ্যাক্টরি প্যাটার্ন", difficulty: "EASY", url: "/subjects/design-patterns" },
        { id: "dp-2", titleEn: "Observer, Strategy & Command Patterns", titleBn: "অবজার্ভার ও স্ট্র্যাটেজি প্যাটার্ন", difficulty: "MEDIUM", url: "/subjects/design-patterns" },
        { id: "dp-3", titleEn: "Decorator, Adapter & Facade Patterns", titleBn: "ডেকোরেটর ও অ্যাডাপ্টার প্যাটার্ন", difficulty: "MEDIUM", url: "/subjects/design-patterns" },
        { id: "dp-4", titleEn: "Repository & Unit of Work Pattern in .NET", titleBn: "রিপোজিটরি ও ইউনিট অব ওয়ার্ক", difficulty: "HARD", url: "/subjects/design-patterns" },
      ],
    },
    {
      id: "os",
      labelEn: "Operating Systems",
      labelBn: "অপারেটিং সিস্টেম",
      x: 480,
      y: 430,
      width: 180,
      height: 52,
      category: "Infrastructure",
      icon: "Terminal",
      prerequisites: [
        { id: "csharp", titleEn: "Memory Basics", titleBn: "মেমোরি বেসিক", subtitleEn: "Stack and Heap", subtitleBn: "স্ট্যাক ও হিপ মেমোরি", url: "/subjects/csharp" },
      ],
      children: ["system-design", "networks"],
      problems: [
        { id: "os-1", titleEn: "Processes vs Threads, Context Switching", titleBn: "প্রসেস বনাম থ্রেড", difficulty: "EASY", url: "/subjects/os" },
        { id: "os-2", titleEn: "Deadlocks: Necessary Conditions & Bankers Algorithm", titleBn: "ডেডলক ও সমাধান কৌশল", difficulty: "MEDIUM", url: "/subjects/os" },
        { id: "os-3", titleEn: "Virtual Memory, Paging, Page Faults & LRU", titleBn: "ভার্চুয়াল মেমোরি ও পেজিং", difficulty: "HARD", url: "/subjects/os" },
        { id: "os-4", titleEn: "Concurrency Synchronization: Mutex, Semaphore, Spinlock", titleBn: "মিউটেক্স ও সেমাফোর সিঙ্ক", difficulty: "HARD", url: "/subjects/os" },
      ],
    },
    {
      id: "networks",
      labelEn: "Computer Networks",
      labelBn: "কম্পিউটার নেটওয়ার্কিং",
      x: 720,
      y: 430,
      width: 190,
      height: 52,
      category: "Infrastructure",
      icon: "Globe",
      prerequisites: [
        { id: "database", titleEn: "Client-Server Flow", titleBn: "ক্লায়েন্ট-সার্ভার আর্কিটেকচার", subtitleEn: "Network calls", subtitleBn: "নেটওয়ার্ক অনুরোধ", url: "/subjects/database" },
      ],
      children: ["system-design"],
      problems: [
        { id: "netw-1", titleEn: "OSI 7 Layers vs TCP/IP Protocol Stack", titleBn: "OSI ও TCP/IP মডেল", difficulty: "EASY", url: "/subjects/networks" },
        { id: "netw-2", titleEn: "TCP 3-Way Handshake vs UDP Reliability Tradeoffs", titleBn: "TCP থ্রি-ওয়ে হ্যান্ডশেক", difficulty: "MEDIUM", url: "/subjects/networks" },
        { id: "netw-3", titleEn: "HTTP/1.1 vs HTTP/2 vs HTTP/3 & WebSockets", titleBn: "HTTP ভার্সন ও ওয়েবসকেট", difficulty: "MEDIUM", url: "/subjects/networks" },
        { id: "netw-4", titleEn: "DNS Resolution, TLS/SSL Handshake & Certificates", titleBn: "ডিএনএস ও টিএলএস এনক্রিপশন", difficulty: "HARD", url: "/subjects/networks" },
      ],
    },
    {
      id: "system-design",
      labelEn: "System Design",
      labelBn: "সিস্টেম ডিজাইন",
      x: 370,
      y: 570,
      width: 190,
      height: 52,
      category: "Architecture",
      icon: "Network",
      badge: "Senior / Lead",
      prerequisites: [
        { id: "database", titleEn: "Databases", titleBn: "ডেটাবেজ", subtitleEn: "Sharding and Replication", subtitleBn: "রেপ্লিকেশন ও শার্ডিং", url: "/subjects/database" },
        { id: "networks", titleEn: "Networking", titleBn: "নেটওয়ার্কিং", subtitleEn: "Load Balancers & DNS", subtitleBn: "লোড ব্যালেন্সার", url: "/subjects/networks" },
      ],
      children: ["behavioral"],
      problems: [
        { id: "sd-1", titleEn: "Horizontal vs Vertical Scaling, Load Balancing (Nginx, HAProxy)", titleBn: "স্কেলিং ও লোড ব্যালেন্সার", difficulty: "MEDIUM", url: "/subjects/system-design" },
        { id: "sd-2", titleEn: "Caching Strategies: Redis, Memcached, Cache-Aside & Eviction", titleBn: "ক্যাশিং কৌশল ও রেডিস", difficulty: "MEDIUM", url: "/subjects/system-design" },
        { id: "sd-3", titleEn: "CAP Theorem, Eventual Consistency & PACELC", titleBn: "সিএপি উপপাদ্য ও কনসিস্টেন্সি", difficulty: "HARD", url: "/subjects/system-design" },
        { id: "sd-4", titleEn: "Message Queues: Kafka vs RabbitMQ, Asynchronous Workflows", titleBn: "মেসেজ ব্রোকার ও কাফকা", difficulty: "HARD", url: "/subjects/system-design" },
        { id: "sd-5", titleEn: "Design URL Shortener (TinyURL) End-to-End", titleBn: "TinyURL সিস্টেম ডিজাইন প্রজেক্ট", difficulty: "HARD", url: "/subjects/system-design" },
      ],
    },
    {
      id: "ai-ml",
      labelEn: "AI & Machine Learning",
      labelBn: "মেশিন লার্নিং ধারণা",
      x: 630,
      y: 570,
      width: 190,
      height: 52,
      category: "Emerging Tech",
      icon: "Brain",
      prerequisites: [
        { id: "dsa", titleEn: "Algorithms", titleBn: "অ্যালগরিদম", subtitleEn: "Math foundations", subtitleBn: "গাণিতিক ভিত্তি", url: "/subjects/dsa" },
      ],
      children: ["behavioral"],
      problems: [
        { id: "ai-1", titleEn: "Supervised vs Unsupervised vs Reinforcement Learning", titleBn: "মেশিন লার্নিং টাইপস", difficulty: "EASY", url: "/subjects/ai-ml" },
        { id: "ai-2", titleEn: "Gradient Descent, Cost Functions & Overfitting (Regularization)", titleBn: "গ্রেডিয়েন্ট ডিসেন্ট ও রেগুলারাইজেশন", difficulty: "MEDIUM", url: "/subjects/ai-ml" },
        { id: "ai-3", titleEn: "Neural Network Architecture, Activation Functions & Transformers", titleBn: "নিউরাল নেটওয়ার্ক ও ট্রান্সফরমার", difficulty: "HARD", url: "/subjects/ai-ml" },
      ],
    },
    {
      id: "behavioral",
      labelEn: "Behavioral & HR Round",
      labelBn: "আচরণমূলক সাক্ষাৎকার প্রস্তুতি",
      x: 480,
      y: 720,
      width: 220,
      height: 52,
      category: "Interview Mastery",
      icon: "Users",
      badge: "Final Step",
      prerequisites: [
        { id: "system-design", titleEn: "Architecture", titleBn: "আর্কিটেকচার", subtitleEn: "Project story", subtitleBn: "বাস্তব কাজের অভিজ্ঞতা", url: "/subjects/system-design" },
      ],
      children: [],
      problems: [
        { id: "hr-1", titleEn: "STAR Method Mastery: Situation, Task, Action, Result", titleBn: "STAR মেথডে উত্তর গঠন", difficulty: "EASY", url: "/subjects/behavioral" },
        { id: "hr-2", titleEn: "Handling Conflict & Challenging Engineering Scenarios", titleBn: "টিম কনফ্লিক্ট ও চ্যালেঞ্জ মোকাবেলা", difficulty: "MEDIUM", url: "/subjects/behavioral" },
        { id: "hr-3", titleEn: "Salary Negotiation & Technical Communication for BD Companies", titleBn: "বেতন আলোচনা ও প্রস্তুতি কৌশল", difficulty: "MEDIUM", url: "/subjects/behavioral" },
      ],
    },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
// 2. NeetCode 150 DSA & Coding Interview Roadmap
// ─────────────────────────────────────────────────────────────────────────────
export const NEETCODE_DSA_ROADMAP: RoadmapTrack = {
  id: "dsa-neetcode",
  titleEn: "NeetCode 150 DSA Flow",
  titleBn: "নিটকড ১৫০ ডেটা স্ট্রাকচার ও অ্যালগরিদম",
  descriptionEn: "Authentic algorithmic dependency graph for technical coding interviews.",
  descriptionBn: "কোডিং ইন্টারভিউয়ের জন্য নিখুঁত অ্যালগরিদমিক নির্ভরতা গ্রাফ।",
  icon: "Binary",
  canvasWidth: 1000,
  canvasHeight: 1050,
  nodes: [
    {
      id: "arrays-hashing",
      labelEn: "Arrays & Hashing",
      labelBn: "অ্যারে ও হ্যাশিং",
      x: 470,
      y: 40,
      width: 170,
      height: 48,
      category: "Foundations",
      badge: "Start Here",
      prerequisites: [],
      children: ["two-pointers", "stack"],
      problems: [
        { id: "nc-1", titleEn: "Contains Duplicate", titleBn: "ডুপ্লিকেট উপাদান নির্ণয়", difficulty: "EASY", url: "/problems" },
        { id: "nc-2", titleEn: "Valid Anagram", titleBn: "অ্যানাগ্রাম পরীক্ষা", difficulty: "EASY", url: "/problems" },
        { id: "nc-3", titleEn: "Two Sum", titleBn: "টু সাম সমস্যা", difficulty: "EASY", url: "/problems" },
        { id: "nc-4", titleEn: "Group Anagrams", titleBn: "অ্যানাগ্রাম গুচ্ছকরণ", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-5", titleEn: "Top K Frequent Elements", titleBn: "টপ K সর্বাধিক উপাদান", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-6", titleEn: "Product of Array Except Self", titleBn: "নিজ ব্যতীত বাকি উপাদানের গুণফল", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-7", titleEn: "Valid Sudoku", titleBn: "সুডোকু যাচাইকরণ", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-8", titleEn: "Encode and Decode Strings", titleBn: "স্ট্রিং এনকোড ও ডিকোড", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-9", titleEn: "Longest Consecutive Sequence", titleBn: "দীর্ঘতম ধারাবাহিক সিকোয়েন্স", difficulty: "MEDIUM", url: "/problems" },
      ],
    },
    {
      id: "two-pointers",
      labelEn: "Two Pointers",
      labelBn: "টু পয়েন্টার টেকনিক",
      x: 350,
      y: 150,
      width: 160,
      height: 48,
      category: "Pointers",
      prerequisites: [
        { id: "arrays-hashing", titleEn: "Arrays & Hashing", titleBn: "অ্যারে ও হ্যাশিং", subtitleEn: "Indexed access", subtitleBn: "ইনডেক্সড অ্যাক্সেস", url: "/problems" },
      ],
      children: ["binary-search", "sliding-window", "linked-list"],
      problems: [
        { id: "nc-10", titleEn: "Valid Palindrome", titleBn: "প্যালিনড্রোম যাচাই", difficulty: "EASY", url: "/problems" },
        { id: "nc-11", titleEn: "Two Sum II - Input Array Is Sorted", titleBn: "সর্টেড অ্যারে টু সাম", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-12", titleEn: "3Sum", titleBn: "থ্রি সাম সমস্যা", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-13", titleEn: "Container With Most Water", titleBn: "সর্বোচ্চ পানির কন্টেইনার", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-14", titleEn: "Trapping Rain Water", titleBn: "বৃষ্টির পানি ট্র্যাপিং", difficulty: "HARD", url: "/problems" },
      ],
    },
    {
      id: "stack",
      labelEn: "Stack",
      labelBn: "স্ট্যাক ডেটা স্ট্রাকচার",
      x: 580,
      y: 150,
      width: 150,
      height: 48,
      category: "Linear Data Structures",
      prerequisites: [
        { id: "arrays-hashing", titleEn: "Arrays & Hashing", titleBn: "অ্যারে ও হ্যাশিং", subtitleEn: "LIFO concepts", subtitleBn: "LIFO পদ্ধতি", url: "/problems" },
      ],
      children: [],
      problems: [
        { id: "nc-15", titleEn: "Valid Parentheses", titleBn: "বন্ধনী শুদ্ধতা যাচাই", difficulty: "EASY", url: "/problems" },
        { id: "nc-16", titleEn: "Min Stack", titleBn: "মিন স্ট্যাক বাস্তবায়ন", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-17", titleEn: "Evaluate Reverse Polish Notation", titleBn: "রিভার্স পোলিশ নোটেশন", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-18", titleEn: "Generate Parentheses", titleBn: "বন্ধনী কম্বিনেশন তৈরি", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-19", titleEn: "Daily Temperatures", titleBn: "দৈনিক তাপমাত্রা", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-20", titleEn: "Car Fleet", titleBn: "কার ফ্লিট সমস্যা", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-21", titleEn: "Largest Rectangle in Histogram", titleBn: "হিস্টোগ্রামে বৃহত্তম আয়তক্ষেত্র", difficulty: "HARD", url: "/problems" },
      ],
    },
    {
      id: "binary-search",
      labelEn: "Binary Search",
      labelBn: "বাইনারি সার্চ",
      x: 230,
      y: 270,
      width: 160,
      height: 48,
      category: "Search",
      prerequisites: [
        { id: "two-pointers", titleEn: "Two Pointers", titleBn: "টু পয়েন্টার", subtitleEn: "Sorted ranges", subtitleBn: "সর্টেড রেঞ্জ", url: "/problems" },
      ],
      children: ["trees"],
      problems: [
        { id: "nc-22", titleEn: "Binary Search", titleBn: "বাইনারি সার্চ বেসিক", difficulty: "EASY", url: "/problems" },
        { id: "nc-23", titleEn: "Search a 2D Matrix", titleBn: "2D ম্যাট্রিক্সে অনুসন্ধান", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-24", titleEn: "Koko Eating Bananas", titleBn: "কোকোর কলা খাওয়া", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-25", titleEn: "Find Minimum in Rotated Sorted Array", titleBn: "রোটেটেড অ্যারেতে সর্বনিম্ন উপাদান", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-26", titleEn: "Search in Rotated Sorted Array", titleBn: "রোটেটেড অ্যারেতে অনুসন্ধান", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-27", titleEn: "Time Based Key-Value Store", titleBn: "টাইম বেসড কি-ভ্যালু স্টোর", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-28", titleEn: "Median of Two Sorted Arrays", titleBn: "দুটি সর্টেড অ্যারের মিডিয়ান", difficulty: "HARD", url: "/problems" },
      ],
    },
    {
      id: "sliding-window",
      labelEn: "Sliding Window",
      labelBn: "স্লাইডিং উইন্ডো",
      x: 430,
      y: 270,
      width: 160,
      height: 48,
      category: "Pointers",
      prerequisites: [
        { id: "two-pointers", titleEn: "Two Pointers", titleBn: "টু পয়েন্টার", subtitleEn: "Continuous subarrays", subtitleBn: "সাবঅ্যারে সমস্যা", url: "/problems" },
      ],
      children: ["trees"],
      problems: [
        { id: "nc-29", titleEn: "Best Time to Buy and Sell Stock", titleBn: "শেয়ার ক্রয়-বিক্রয় লাভ", difficulty: "EASY", url: "/problems" },
        { id: "nc-30", titleEn: "Longest Substring Without Repeating Characters", titleBn: "অনন্য অক্ষরের দীর্ঘতম সাবস্ট্রিং", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-31", titleEn: "Longest Repeating Character Replacement", titleBn: "অক্ষর রূপান্তরের দীর্ঘতম সাবস্ট্রিং", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-32", titleEn: "Permutation in String", titleBn: "স্ট্রিং বিন্যাস খোঁজা", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-33", titleEn: "Minimum Window Substring", titleBn: "ক্ষুদ্রতম উইন্ডো সাবস্ট্রিং", difficulty: "HARD", url: "/problems" },
        { id: "nc-34", titleEn: "Sliding Window Maximum", titleBn: "স্লাইডিং উইন্ডো সর্বোচ্চ মান", difficulty: "HARD", url: "/problems" },
      ],
    },
    {
      id: "linked-list",
      labelEn: "Linked List",
      labelBn: "লিঙ্কড লিস্ট",
      x: 640,
      y: 270,
      width: 160,
      height: 48,
      category: "Linear Data Structures",
      prerequisites: [
        { id: "two-pointers", titleEn: "Two Pointers", titleBn: "টু পয়েন্টার", subtitleEn: "Node pointers", subtitleBn: "নোড রেফারেন্স", url: "/problems" },
      ],
      children: ["trees"],
      problems: [
        { id: "nc-35", titleEn: "Reverse Linked List", titleBn: "লিঙ্কড লিস্ট বিপরীতকরণ", difficulty: "EASY", url: "/problems" },
        { id: "nc-36", titleEn: "Merge Two Sorted Lists", titleBn: "দুটি সর্টেড লিস্ট একত্রিতকরণ", difficulty: "EASY", url: "/problems" },
        { id: "nc-37", titleEn: "Reorder List", titleBn: "লিস্ট পুনর্বিন্যাস", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-38", titleEn: "Remove Nth Node From End of List", titleBn: "শেষ থেকে N-তম নোড অপসারণ", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-39", titleEn: "Copy List with Random Pointer", titleBn: "র‍্যান্ডম পয়েন্টারসহ কপি", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-40", titleEn: "Add Two Numbers", titleBn: "দুটি সংখ্যার যোগফল", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-41", titleEn: "Linked List Cycle", titleBn: "লিস্টে সাইকেল শনাক্তকরণ", difficulty: "EASY", url: "/problems" },
        { id: "nc-42", titleEn: "Merge K Sorted Lists", titleBn: "K টি সর্টেড লিস্ট মার্জ", difficulty: "HARD", url: "/problems" },
        { id: "nc-43", titleEn: "Reverse Nodes in k-Group", titleBn: "K গ্রুপে নোড বিপরীতকরণ", difficulty: "HARD", url: "/problems" },
      ],
    },
    {
      id: "trees",
      labelEn: "Trees",
      labelBn: "ট্রি ডেটা স্ট্রাকচার",
      x: 430,
      y: 390,
      width: 160,
      height: 48,
      category: "Hierarchical",
      badge: "Core Pivot",
      prerequisites: [
        { id: "binary-search", titleEn: "Binary Search", titleBn: "বাইনারি সার্চ", subtitleEn: "BST lookup", subtitleBn: "বাইনারি সার্চ ট্রি", url: "/problems" },
        { id: "linked-list", titleEn: "Linked List", titleBn: "লিঙ্কড লিস্ট", subtitleEn: "Pointer structures", subtitleBn: "পয়েন্টার নোড", url: "/problems" },
      ],
      children: ["tries", "heap", "backtracking"],
      problems: [
        { id: "nc-44", titleEn: "Invert Binary Tree", titleBn: "বাইনারি ট্রি বিপরীতকরণ", difficulty: "EASY", url: "/problems" },
        { id: "nc-45", titleEn: "Maximum Depth of Binary Tree", titleBn: "বাইনারি ট্রির সর্বোচ্চ গভীরতা", difficulty: "EASY", url: "/problems" },
        { id: "nc-46", titleEn: "Diameter of Binary Tree", titleBn: "বাইনারি ট্রির ব্যাস", difficulty: "EASY", url: "/problems" },
        { id: "nc-47", titleEn: "Balanced Binary Tree", titleBn: "ব্যালান্সড বাইনারি ট্রি", difficulty: "EASY", url: "/problems" },
        { id: "nc-48", titleEn: "Same Tree", titleBn: "একই ট্রি যাচাইকরণ", difficulty: "EASY", url: "/problems" },
        { id: "nc-49", titleEn: "Subtree of Another Tree", titleBn: "সাবট্রি নিশ্চিতকরণ", difficulty: "EASY", url: "/problems" },
        { id: "nc-50", titleEn: "Lowest Common Ancestor of a BST", titleBn: "নিকটতম সাধারণ পূর্বপুরুষ", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-51", titleEn: "Binary Tree Level Order Traversal", titleBn: "লেভেল অর্ডার ট্রাভার্সাল (BFS)", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-52", titleEn: "Validate Binary Search Tree", titleBn: "BST সঠিকতা যাচাই", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-53", titleEn: "Kth Smallest Element in a BST", titleBn: "K-তম ক্ষুদ্রতম উপাদান", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-54", titleEn: "Serialize and Deserialize Binary Tree", titleBn: "ট্রি সিরিয়ালাইজ ও ডিসিরিয়ালাইজ", difficulty: "HARD", url: "/problems" },
      ],
    },
    {
      id: "tries",
      labelEn: "Tries",
      labelBn: "ট্রাই (প্রিফিক্স ট্রি)",
      x: 250,
      y: 500,
      width: 150,
      height: 48,
      category: "Hierarchical",
      prerequisites: [
        { id: "trees", titleEn: "Trees", titleBn: "ট্রি", subtitleEn: "Multi-way branches", subtitleBn: "বহুমাত্রিক শাখা", url: "/problems" },
      ],
      children: [],
      problems: [
        { id: "nc-55", titleEn: "Implement Trie (Prefix Tree)", titleBn: "ট্রাই বাস্তবায়ন", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-56", titleEn: "Design Add and Search Words Data Structure", titleBn: "শব্দ যোগ ও অনুসন্ধান স্ট্রাকচার", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-57", titleEn: "Word Search II", titleBn: "শব্দ অনুসন্ধান ২", difficulty: "HARD", url: "/problems" },
      ],
    },
    {
      id: "heap",
      labelEn: "Heap / Priority Queue",
      labelBn: "হিপ ও প্রায়োরিটি কিউ",
      x: 390,
      y: 610,
      width: 180,
      height: 48,
      category: "Hierarchical",
      prerequisites: [
        { id: "trees", titleEn: "Trees", titleBn: "ট্রি", subtitleEn: "Complete binary trees", subtitleBn: "কমপ্লিট বাইনারি ট্রি", url: "/problems" },
      ],
      children: ["intervals", "greedy", "advanced-graphs"],
      problems: [
        { id: "nc-58", titleEn: "Kth Largest Element in a Stream", titleBn: "স্ট্রিমের K-তম বৃহত্তম উপাদান", difficulty: "EASY", url: "/problems" },
        { id: "nc-59", titleEn: "Last Stone Weight", titleBn: "পাথর ভাঙার খেলা", difficulty: "EASY", url: "/problems" },
        { id: "nc-60", titleEn: "K Closest Points to Origin", titleBn: "মূলবিন্দুর K টি নিকটতম বিন্দু", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-61", titleEn: "Task Scheduler", titleBn: "টাস্ক শিডিউলার", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-62", titleEn: "Design Twitter", titleBn: "টুইটার ফিড ডিজাইন", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-63", titleEn: "Find Median from Data Stream", titleBn: "ডেটা স্ট্রিম থেকে মিডিয়ান", difficulty: "HARD", url: "/problems" },
      ],
    },
    {
      id: "backtracking",
      labelEn: "Backtracking",
      labelBn: "ব্যাকট্র্যাকিং",
      x: 570,
      y: 500,
      width: 160,
      height: 48,
      category: "Algorithm Paradigm",
      prerequisites: [
        { id: "trees", titleEn: "Trees", titleBn: "ট্রি", subtitleEn: "Recursion & state tree", subtitleBn: "রিকRecursive স্টেট", url: "/problems" },
      ],
      children: ["graphs", "1d-dp"],
      problems: [
        { id: "nc-64", titleEn: "Subsets", titleBn: "সাবসেট তৈরি", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-65", titleEn: "Combination Sum", titleBn: "কম্বিনেশন সাম", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-66", titleEn: "Permutations", titleBn: "পারমুটেশন বিন্যাস", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-67", titleEn: "Subsets II", titleBn: "সাবসেট ২ (ডুপ্লিকেটসহ)", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-68", titleEn: "Word Search", titleBn: "গ্রিডে শব্দ অনুসন্ধান", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-69", titleEn: "Palindrome Partitioning", titleBn: "প্যালিনড্রোম বিভাজন", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-70", titleEn: "N-Queens", titleBn: "এন-কুইন্স সমস্যা", difficulty: "HARD", url: "/problems" },
      ],
    },
    {
      id: "graphs",
      labelEn: "Graphs",
      labelBn: "গ্রাফ অ্যালগরিদম",
      x: 530,
      y: 630,
      width: 150,
      height: 48,
      category: "Advanced Graph",
      prerequisites: [
        { id: "backtracking", titleEn: "Backtracking", titleBn: "ব্যাকট্র্যাকিং", subtitleEn: "DFS exploration", subtitleBn: "DFS অনুসন্ধান", url: "/problems" },
      ],
      children: ["advanced-graphs", "2d-dp"],
      problems: [
        { id: "nc-71", titleEn: "Number of Islands", titleBn: "দ্বীপের সংখ্যা গণনা", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-72", titleEn: "Max Area of Island", titleBn: "দ্বীপের সর্বোচ্চ ক্ষেত্রফল", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-73", titleEn: "Clone Graph", titleBn: "গ্রাফ ক্লোন তৈরি", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-74", titleEn: "Rotting Oranges", titleBn: "পচা কমলার সময়কাল (BFS)", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-75", titleEn: "Pacific Atlantic Water Flow", titleBn: "জল প্রবাহ বিশ্লেষণ", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-76", titleEn: "Course Schedule", titleBn: "কোর্স শিডিউলিং (Topological Sort)", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-77", titleEn: "Redundant Connection", titleBn: "অতিরিক্ত সংযোগ (Union Find)", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-78", titleEn: "Word Ladder", titleBn: "শব্দ রূপান্তর মই", difficulty: "HARD", url: "/problems" },
      ],
    },
    {
      id: "1d-dp",
      labelEn: "1-D Dynamic Programming",
      labelBn: "১-ডি ডায়নামিক প্রোগ্রামিং",
      x: 720,
      y: 630,
      width: 190,
      height: 48,
      category: "Optimization",
      prerequisites: [
        { id: "backtracking", titleEn: "Backtracking", titleBn: "ব্যাকট্র্যাকিং", subtitleEn: "Memoized branches", subtitleBn: "মেমোইজেশন কৌশল", url: "/problems" },
      ],
      children: ["2d-dp", "bit-manipulation"],
      problems: [
        { id: "nc-79", titleEn: "Climbing Stairs", titleBn: "সিঁড়ি ওঠার উপায়", difficulty: "EASY", url: "/problems" },
        { id: "nc-80", titleEn: "Min Cost Climbing Stairs", titleBn: "সর্বনিম্ন খরচে সিঁড়ি অতিক্রম", difficulty: "EASY", url: "/problems" },
        { id: "nc-81", titleEn: "House Robber", titleBn: "চোরের চুরি পরিকল্পনা", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-82", titleEn: "House Robber II", titleBn: "বৃত্তাকার হাউজ রবার", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-83", titleEn: "Longest Palindromic Substring", titleBn: "দীর্ঘতম প্যালিনড্রোমিক সাবস্ট্রিং", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-84", titleEn: "Coin Change", titleBn: "কয়েন চেঞ্জ সমস্যা", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-85", titleEn: "Maximum Product Subarray", titleBn: "সর্বোচ্চ গুণফলের সাবঅ্যারে", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-86", titleEn: "Word Break", titleBn: "শব্দ বিভাজন সম্ভব কি না", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-87", titleEn: "Longest Increasing Subsequence", titleBn: "দীর্ঘতম ক্রমবর্ধমান সিকোয়েন্স", difficulty: "MEDIUM", url: "/problems" },
      ],
    },
    {
      id: "intervals",
      labelEn: "Intervals",
      labelBn: "ইন্টারভালস",
      x: 170,
      y: 740,
      width: 150,
      height: 48,
      category: "Array Heuristics",
      prerequisites: [
        { id: "heap", titleEn: "Heap", titleBn: "হিপ", subtitleEn: "Sorted endpoints", subtitleBn: "সর্টেড এন্ডপয়েন্ট", url: "/problems" },
      ],
      children: [],
      problems: [
        { id: "nc-88", titleEn: "Insert Interval", titleBn: "ইন্টারভাল সন্নিবেশ", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-89", titleEn: "Merge Intervals", titleBn: "ইন্টারভাল একত্রীকরণ", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-90", titleEn: "Non-overlapping Intervals", titleBn: "ওভারল্যাপহীন ইন্টারভাল সংখ্যা", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-91", titleEn: "Meeting Rooms II", titleBn: "মিটিং রুম সংখ্যা নির্ধারণ", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-92", titleEn: "Minimum Interval to Include Each Query", titleBn: "ন্যূনতম ইন্টারভাল অনুসন্ধান", difficulty: "HARD", url: "/problems" },
      ],
    },
    {
      id: "greedy",
      labelEn: "Greedy",
      labelBn: "গ্রিডি অ্যালগরিদম",
      x: 320,
      y: 770,
      width: 150,
      height: 48,
      category: "Algorithm Paradigm",
      prerequisites: [
        { id: "heap", titleEn: "Heap", titleBn: "হিপ", subtitleEn: "Local optima", subtitleBn: "লোকাল অপটিমাম বাছাই", url: "/problems" },
      ],
      children: [],
      problems: [
        { id: "nc-93", titleEn: "Maximum Subarray", titleBn: "সর্বোচ্চ সাবঅ্যারে যোগফল (Kadane)", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-94", titleEn: "Jump Game", titleBn: "লাফিয়ে গন্তব্যে পৌঁছানো", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-95", titleEn: "Gas Station", titleBn: "গ্যাস স্টেশন চক্র", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-96", titleEn: "Hand of Straights", titleBn: "ধারাবাহিক তাসের হাত", difficulty: "MEDIUM", url: "/problems" },
      ],
    },
    {
      id: "advanced-graphs",
      labelEn: "Advanced Graphs",
      labelBn: "উন্নত গ্রাফ অ্যালগরিদম",
      x: 440,
      y: 750,
      width: 170,
      height: 48,
      category: "Advanced Graph",
      prerequisites: [
        { id: "heap", titleEn: "Heap", titleBn: "হিপ", subtitleEn: "Dijkstra Priority Queue", subtitleBn: "ডায়াক্সট্রা কিউ", url: "/problems" },
        { id: "graphs", titleEn: "Graphs", titleBn: "গ্রাফ", subtitleEn: "MST & Flow", subtitleBn: "মিনিমাম স্প্যানিং ট্রি", url: "/problems" },
      ],
      children: [],
      problems: [
        { id: "nc-97", titleEn: "Reconstruct Itinerary", titleBn: "ভ্রমণপথ পুনর্নির্মাণ (Hierholzer)", difficulty: "HARD", url: "/problems" },
        { id: "nc-98", titleEn: "Min Cost to Connect All Points", titleBn: "সকল বিন্দু সংযোগের খরচ (Prim/Kruskal)", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-99", titleEn: "Network Delay Time", titleBn: "নেটওয়ার্ক বিলম্ব সময় (Dijkstra)", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-100", titleEn: "Swim in Rising Water", titleBn: "ক্রমবর্ধমান জলে সাঁতার", difficulty: "HARD", url: "/problems" },
        { id: "nc-101", titleEn: "Alien Dictionary", titleBn: "ভিনগ্রহের বর্ণমালা বিন্যাস", difficulty: "HARD", url: "/problems" },
      ],
    },
    {
      id: "2d-dp",
      labelEn: "2-D Dynamic Programming",
      labelBn: "২-ডি ডায়নামিক প্রোগ্রামিং",
      x: 580,
      y: 770,
      width: 190,
      height: 48,
      category: "Optimization",
      prerequisites: [
        { id: "1d-dp", titleEn: "1-D DP", titleBn: "১-ডি DP", subtitleEn: "Subproblem matrix", subtitleBn: "ম্যাট্রিক্স সাবপ্রবলেম", url: "/problems" },
        { id: "graphs", titleEn: "Graphs", titleBn: "গ্রাফ", subtitleEn: "Grid traversal", subtitleBn: "গ্রিড পাথ ট্রাভার্সাল", url: "/problems" },
      ],
      children: ["math-geometry"],
      problems: [
        { id: "nc-102", titleEn: "Unique Paths", titleBn: "অনন্য পথের সংখ্যা", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-103", titleEn: "Longest Common Subsequence", titleBn: "দীর্ঘতম সাধারণ সাবসিকোয়েন্স (LCS)", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-104", titleEn: "Best Time to Buy and Sell Stock with Cooldown", titleBn: "কুলডাউনসহ শেয়ার ট্রেডিং", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-105", titleEn: "Coin Change II", titleBn: "কয়েন চেঞ্জ ২ (আনলিমিটেড কম্বিনেশন)", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-106", titleEn: "Target Sum", titleBn: "টার্গেট সাম", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-107", titleEn: "Edit Distance", titleBn: "এডিট ডিসট্যান্স (Levenshtein)", difficulty: "HARD", url: "/problems" },
        { id: "nc-108", titleEn: "Burst Balloons", titleBn: "বেলুন ফাটানোর সর্বোচ্চ কয়েন", difficulty: "HARD", url: "/problems" },
      ],
    },
    {
      id: "bit-manipulation",
      labelEn: "Bit Manipulation",
      labelBn: "বিট ম্যানিপুলেশন",
      x: 770,
      y: 760,
      width: 170,
      height: 48,
      category: "Bitwise",
      prerequisites: [
        { id: "1d-dp", titleEn: "1-D DP", titleBn: "১-ডি DP", subtitleEn: "Bitmask DP", subtitleBn: "বিটমাস্কিং", url: "/problems" },
      ],
      children: ["math-geometry"],
      problems: [
        { id: "nc-109", titleEn: "Single Number", titleBn: "একক সংখ্যা শনাক্তকরণ (XOR)", difficulty: "EASY", url: "/problems" },
        { id: "nc-110", titleEn: "Number of 1 Bits", titleBn: "১ বিটের সংখ্যা গণনা (Hamming Weight)", difficulty: "EASY", url: "/problems" },
        { id: "nc-111", titleEn: "Counting Bits", titleBn: "বিট কাউন্টিং ধারা", difficulty: "EASY", url: "/problems" },
        { id: "nc-112", titleEn: "Reverse Bits", titleBn: "বিট বিপরীতকরণ", difficulty: "EASY", url: "/problems" },
        { id: "nc-113", titleEn: "Missing Number", titleBn: "অনুপস্থিত সংখ্যা নির্ণয়", difficulty: "EASY", url: "/problems" },
      ],
    },
    {
      id: "math-geometry",
      labelEn: "Math & Geometry",
      labelBn: "গণিত ও জ্যামিতি",
      x: 670,
      y: 890,
      width: 170,
      height: 48,
      category: "Math",
      prerequisites: [
        { id: "2d-dp", titleEn: "2-D DP", titleBn: "২-ডি DP", subtitleEn: "Matrix properties", subtitleBn: "ম্যাট্রিক্স ট্রান্সফর্মেশন", url: "/problems" },
        { id: "bit-manipulation", titleEn: "Bit Manipulation", titleBn: "বিট ম্যানিপুলেশন", subtitleEn: "Integer arithmetic", subtitleBn: "পূর্ণসংখ্যা পাটিগণিত", url: "/problems" },
      ],
      children: [],
      problems: [
        { id: "nc-114", titleEn: "Rotate Image", titleBn: "ম্যাট্রিক্স ৯০ ডিগ্রি ঘোরানো", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-115", titleEn: "Spiral Matrix", titleBn: "স্পাইরাল ম্যাট্রিক্স ট্রাভার্সাল", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-116", titleEn: "Set Matrix Zeroes", titleBn: "ম্যাট্রিক্সে শূন্য স্থাপন", difficulty: "MEDIUM", url: "/problems" },
        { id: "nc-117", titleEn: "Happy Number", titleBn: "হ্যাপি নাম্বার যাচাই", difficulty: "EASY", url: "/problems" },
        { id: "nc-118", titleEn: "Plus One", titleBn: "এক যোগ সমস্যা", difficulty: "EASY", url: "/problems" },
        { id: "nc-119", titleEn: "Pow(x, n)", titleBn: "পাওয়ার ক্যালকুলেশন O(log n)", difficulty: "MEDIUM", url: "/problems" },
      ],
    },
  ],
};

export const ALL_ROADMAPS = [BD_SWE_ROADMAP, NEETCODE_DSA_ROADMAP];
