import type { LocalLesson } from "@/lib/lessons-data";

export const exceptionsHierarchyLesson: LocalLesson = {
  slug: "exceptions-hierarchy",
  titleEn: "Exception Hierarchy & Filters",
  titleBn: "এক্সেপশন হায়ারার্কি ও এক্সেপশন ফিল্টার (when)",
  categoryEn: "08. Exception Handling",
  categoryBn: "০৮. এক্সেপশন ও ত্রুটি হ্যান্ডলিং",
  categoryDescEn:
    "Structured error handling in .NET: try/catch/finally blocks, stack trace preservation, custom domain exceptions, and exception filters.",
  categoryDescBn:
    ".NET এ ত্রুটি হ্যান্ডলিং: ট্রাই-ক্যাচ-ফাইনালি ব্লক, স্ট্যাক ট্রেস সংরক্ষণ (throw vs throw ex), কাস্টম এক্সেপশন ও এক্সেপশন ফিল্টার।",
  categoryPriority: "NORMAL",
  descriptionEn:
    "The .NET exception inheritance tree, why ApplicationException was deprecated, standard BCL exceptions, and C# 6+ exception filters (when) evaluating on the first-pass stack walk.",
  descriptionBn:
    "CLR এক্সেপশন ট্রি, ApplicationException অবলুপ্তির কারণ, স্ট্যান্ডার্ড BCL এক্সেপশন এবং স্ট্যাক আনওয়াইন্ড হওয়ার আগেই সি# ৬+ when ফিল্টারের কার্যপ্রণালী।",
  difficulty: "MEDIUM",
  displayOrder: 4,
  prerequisites: ["exceptions-try-catch-finally", "exceptions-throw", "exceptions-custom"],
  estimatedMinutes: 25,
  lastUpdated: "Recently updated",
  contentEn: `# Exception Hierarchy & Filters in C#

In the .NET Common Language Runtime (CLR), all exceptions are strongly typed objects governed by a rigorous class inheritance hierarchy. 

Mastering this hierarchy—alongside **Exception Filters** (\`when\` keyword introduced in C# 6)—is essential for writing high-performance, fault-tolerant enterprise applications and performing accurate post-mortem debugging.

---

## The CLR Exception Inheritance Tree

All exceptions in .NET derive directly or indirectly from \`System.Object\`.

\`\`\`
                     System.Object
                           ▲
                           │
                    System.Exception
                  ┌────────┴────────┐
                  │                 │
           SystemException   ApplicationException (Deprecated!)
            ┌─────┴─────────────────────────┐
            │                               │
     NullReferenceException          ArgumentException
     IndexOutOfRangeException         ┌─────┴──────────────┐
     InvalidOperationException        ArgumentNullException ArgumentOutOfRangeException
     FormatException
     DivideByZeroException
\`\`\`

### 1. \`System.Exception\`
The base class for all exceptions in .NET. It encapsulates common diagnostics:
- \`Message\`: Explanatory human-readable text.
- \`StackTrace\`: The execution path from the throw site.
- \`InnerException\`: The antecedent exception that caused the current exception.
- \`Data\`: A key/value dictionary for supplemental context.

### 2. \`System.SystemException\`
The base class for system-level runtime exceptions generated by the CLR execution engine (e.g. \`NullReferenceException\`, \`OutOfMemoryException\`, \`StackOverflowException\`).

### 3. \`System.ApplicationException\` (Deprecated Architectural Anti-Pattern)
- **Original Vision (.NET 1.0)**: Microsoft intended \`SystemException\` for framework/runtime errors and \`ApplicationException\` for user applications and third-party libraries.
- **Why It Failed**: The BCL (Base Class Library) team violated their own guideline by throwing \`SystemException\` subclasses from application-level APIs (such as collections and reflection). Meanwhile, third-party libraries inconsistently inherited from both.
- **Modern .NET Standard**: **Never inherit from \`ApplicationException\`**, and never catch \`ApplicationException\`. Microsoft's official framework design guidelines require creating custom exceptions that inherit directly from \`System.Exception\`.

---

## Standard BCL Exceptions: Selection & Selection Guide

Selecting the appropriate BCL exception type clarifies developer intent and simplifies error recovery:

| Exception Type | When to Throw / Expect | Best Practice Guard |
| :--- | :--- | :--- |
| **\`ArgumentNullException\`** | A method parameter is \`null\` when a valid instance is required. | \`ArgumentNullException.ThrowIfNull(arg);\` |
| **\`ArgumentOutOfRangeException\`** | A parameter has a non-null value outside the allowable range or boundary. | \`ArgumentOutOfRangeException.ThrowIfNegative(index);\` |
| **\`ArgumentException\`** | An argument is invalid for other reasons (e.g., whitespace-only string, invalid enum). | \`throw new ArgumentException("String cannot be empty.", nameof(name));\` |
| **\`InvalidOperationException\`** | The method call is invalid due to the object's current state (not invalid arguments). | Use when calling \`.Read()\` on a closed database connection or stream. |
| **\`NotSupportedException\`** | The requested functionality is permanently unsupported by this specific type or platform. | Throw from a read-only collection's \`.Add()\` method. |
| **\`NotImplementedException\`** | The method or property is stubbed out and not yet implemented during development. | Never allow this to reach production releases. |
| **\`OperationCanceledException\`** | A cooperative cancellation request was triggered via a \`CancellationToken\`. | Standard mechanism in asynchronous APIs (\`cancellationToken.ThrowIfCancellationRequested()\`). |
| **\`KeyNotFoundException\`** | Attempted to access a non-existent dictionary key via the indexer (\`dict[key]\`). | Prefer \`dict.TryGetValue(key, out var val)\` to prevent exception overhead. |

---

## Exception Filters (\`when\` Clause)

C# 6 introduced **Exception Filters** using the \`when\` keyword on \`catch\` blocks:

\`\`\`csharp
catch (HttpRequestException ex) when (ex.StatusCode == HttpStatusCode.NotFound)
{
    Console.WriteLine("Resource does not exist.");
}
\`\`\`

### Under the Hood: The Two-Pass CLR Exception Handling Model
Underneath .NET, Windows Structured Exception Handling (SEH) executes exception processing in **two distinct phases**:

1. **Pass 1: Search Pass (Stack Walk)**:
   - The CLR crawls up the call stack looking for an active \`try/catch\` block that handles the thrown exception type.
   - If a candidate \`catch\` block has a \`when (condition)\` filter, **the CLR evaluates the condition immediately during this first pass**!
   - **Crucial Rule**: The call stack has **NOT been unwound yet**. The stack frames, local variables, and CPU register state between the throw site and the catch handler are completely preserved in memory!
2. **Pass 2: Unwind Pass**:
   - Once a handler whose filter returns \`true\` is identified, the CLR performs the actual stack unwind from the throw site up to that handler, running \`finally\` blocks along the way, before entering the \`catch\` block.

---

## \`catch ... when\` vs \`catch ... { if (...) throw; }\`

The architectural distinction between exception filters and catching followed by rethrowing is profound:

| Characteristic | \`catch (Exception ex) when (cond)\` | \`catch (Exception ex) { if (!cond) throw; }\` |
| :--- | :--- | :--- |
| **Stack Unwinding** | Evaluated **before** stack unwinding. | Stack is **already unwound** to the catch point before condition is tested. |
| **Post-Mortem Dumps** | Crash dumps preserve full call stack, local variables, and object graph at the point of origin. | Intermediate stack frames and local variables are lost/popped. |
| **\`finally\` Execution** | Intervening \`finally\` blocks have **not** run yet if filter returns \`false\`. | Intervening \`finally\` blocks have **already executed**, altering program state prematurely! |
| **Performance** | Bypasses unwinding overhead if condition is \`false\`. | Incurs the expensive performance cost of unwinding and rethrowing. |

\`\`\`csharp
// ANTI-PATTERN: Prematurely unwinds the stack and alters diagnostics
try
{
    ExecuteExternalOperation();
}
catch (SqlException ex)
{
    if (ex.Number != 1205) // Not a deadlock
    {
        throw; // Stack was already unwound to this method!
    }
    HandleDeadlock(ex);
}

// MODERN IDIOMATIC PATTERN: Zero unwinding if not a deadlock!
try
{
    ExecuteExternalOperation();
}
catch (SqlException ex) when (ex.Number == 1205)
{
    HandleDeadlock(ex);
}
\`\`\`

---

## The "Log Without Catching" Pattern

Because filter conditions execute during the **first pass** without unwinding the stack, you can create a diagnostic pass-through filter that logs exceptions at their origin point and always returns \`false\`:

\`\`\`csharp
public static bool LogException(Exception ex)
{
    Logger.LogError(ex, "Telemetry intercepted exception during first-pass stack walk.");
    return false; // Return false so CLR continues searching for the actual handler!
}

// In application code:
try
{
    ProcessOrderPipeline();
}
catch (Exception ex) when (LogException(ex))
{
    // This block is NEVER entered because LogException returns false!
}
\`\`\`

> **Filter Safety Warning**: Exception filter predicates must be side-effect free and should never throw exceptions themselves. If an exception occurs inside a \`when\` clause, the CLR catches it, treats the filter result as \`false\`, and silently ignores the filter failure.

---

## Comprehensive Implementation: Resilience & Error Discrimination

\`\`\`csharp
using System;
using System.Net;
using System.Net.Http;

public class ResilienceHandler
{
    public static void ExecuteWithFilter(int simulatedHttpCode)
    {
        try
        {
            SimulateRemoteCall(simulatedHttpCode);
        }
        catch (HttpRequestException ex) when (ex.StatusCode == HttpStatusCode.RequestTimeout || 
                                              ex.StatusCode == HttpStatusCode.GatewayTimeout)
        {
            Console.WriteLine($"[Transient Timeout] {ex.StatusCode}: Retrying operation...");
        }
        catch (HttpRequestException ex) when (ex.StatusCode == HttpStatusCode.NotFound)
        {
            Console.WriteLine("[Resource Missing] 404 Not Found: Entity does not exist.");
        }
        catch (HttpRequestException ex) when ((int)ex.StatusCode! >= 500 && (int)ex.StatusCode <= 599)
        {
            Console.WriteLine($"[Server Fault] Critical upstream error: {ex.StatusCode}");
        }
        catch (Exception ex) when (LogUncaughtException(ex))
        {
            // Logging interceptor (never entered)
        }
    }

    private static bool LogUncaughtException(Exception ex)
    {
        Console.WriteLine($"[Audit Log] Intercepted {ex.GetType().Name} before unwind: {ex.Message}");
        return false;
    }

    private static void SimulateRemoteCall(int code)
    {
        throw new HttpRequestException($"HTTP {(HttpStatusCode)code}", null, (HttpStatusCode)code);
    }

    public static void Main()
    {
        ExecuteWithFilter(404);
        ExecuteWithFilter(504);
        ExecuteWithFilter(500);
    }
}
\`\`\`

---

## Practical Problem Walkthrough

### Problem: Codeforces Assiut Sheet #1 Problem U (Float or int)
*Given a real number $N$, determine whether it is an integer or a floating-point number. If it is an integer, print \`int {integer_part}\`. If it is a float, print \`float {integer_part} {fractional_part}\`.*

#### Algorithmic Analysis
1. Input format: A string representing a decimal number (e.g. \`234.000\` or \`534.958\`).
2. Type discrimination:
   - Split by \`.\` or parse into decimal.
   - If the fractional part after conversion equals zero, it classifies as an integer.
   - Otherwise, it classifies as a floating-point number.
3. Exception guards: Protect boundary parsing using typed conversions and structured validation.

#### C# Solution

\`\`\`csharp
using System;
using System.Globalization;

public class Program
{
    public static void Main()
    {
        string? input = Console.ReadLine();
        if (string.IsNullOrWhiteSpace(input))
        {
            return;
        }

        try
        {
            ClassifyNumber(input.Trim());
        }
        catch (FormatException ex)
        {
            Console.WriteLine($"[Input Error] Failed to parse input: {ex.Message}");
        }
    }

    public static void ClassifyNumber(string value)
    {
        int dotIndex = value.IndexOf('.');

        if (dotIndex == -1)
        {
            Console.WriteLine($"int {value}");
            return;
        }

        string integerPartStr = value.Substring(0, dotIndex);
        string fractionalPartStr = value.Substring(dotIndex + 1);

        // Parse fraction to inspect if it contains non-zero value
        if (double.TryParse("0." + fractionalPartStr, NumberStyles.Float, CultureInfo.InvariantCulture, out double fractionVal))
        {
            if (fractionVal == 0.0)
            {
                Console.WriteLine($"int {integerPartStr}");
            }
            else
            {
                Console.WriteLine($"float {integerPartStr} 0.{fractionalPartStr}");
            }
        }
        else
        {
            throw new FormatException($"Invalid numeric format in fraction: {fractionalPartStr}");
        }
    }
}
\`\`\`

#### Complexity Analysis
- **Time Complexity**: $\\mathcal{O}(L)$ where $L$ is the length of the input number string ($L \\le 100$). Finding the decimal point and substring extraction runs in linear time relative to digits.
- **Space Complexity**: $\\mathcal{O}(L)$ for the substring allocations of integer and fractional components.

---

## Recommended Practice Problems

| Status | Source | Problem Name | Difficulty | Focus Concepts |
| :---: | :--- | :--- | :--- | :--- |
| ⚪ | Codeforces | [Assiut Sheet #1: Float or int](https://codeforces.com/group/MWSDmqGsZm/contest/219158/problem/U) | Easy | Number parsing, String discrimination, Guard clauses |
| ⚪ | Codeforces | [Assiut Sheet #1: Comparison](https://codeforces.com/group/MWSDmqGsZm/contest/219158/problem/V) | Easy | Conditional branches, Relational evaluation, Input validation |
| ⚪ | Exercism C# | [Attack of the Trolls](https://exercism.org/tracks/csharp/exercises/attack-of-the-trolls) | Medium | Exception filters (\`when\`), Role permission checking |
| ⚪ | Exercism C# | [Calculator Conundrum](https://exercism.org/tracks/csharp/exercises/calculator-conundrum) | Medium | BCL exception hierarchy, ArgumentNullException, InvalidOperationException |
`,

  contentBn: `# C# এ এক্সেপশন হায়ারার্কি ও এক্সেপশন ফিল্টার (when)

.NET Common Language Runtime (CLR)-এ সকল এক্সেপশন হচ্ছে স্ট্রংলি টাইপড অবজেক্ট যা একটি সুনির্দিষ্ট ক্লাস ইনহেরিটেন্স হায়ারার্কির অন্তর্ভুক্ত।

এই এক্সেপশন হায়ারার্কি এবং সি# ৬-এ যুক্ত হওয়া **এক্সেপশন ফিল্টার (\`when\` কি-ওয়ার্ড)** সঠিকভাবে আয়ত্ত করা উচ্চ ক্ষমতাসম্পন্ন ও ত্রুটি-সহনশীল এন্টারপ্রাইজ অ্যাপ্লিকেশন তৈরির জন্য অত্যন্ত গুরুত্বপূর্ণ।

---

## CLR এক্সেপশন ইনহেরিটেন্স ট্রি

.NET-এ প্রতিটি এক্সেপশন প্রত্যক্ষ বা পরোক্ষভাবে \`System.Object\` থেকে ইনহেরিট করে।

\`\`\`
                     System.Object
                           ▲
                           │
                    System.Exception
                  ┌────────┴────────┐
                  │                 │
           SystemException   ApplicationException (Deprecated!)
            ┌─────┴─────────────────────────┐
            │                               │
     NullReferenceException          ArgumentException
     IndexOutOfRangeException         ┌─────┴──────────────┐
     InvalidOperationException        ArgumentNullException ArgumentOutOfRangeException
     FormatException
     DivideByZeroException
\`\`\`

### ১. \`System.Exception\`
সকল .NET এক্সেপশনের মূল ভিত্তি। এতে ত্রুটির সার্বিক তথ্য থাকে:
- \`Message\`: মানুষের পাঠযোগ্য ত্রুটির বিবরণ।
- \`StackTrace\`: এক্সিকিউশন স্ট্যাকের কল পাথ।
- \`InnerException\`: মূল কারণ নির্দেশকারী পূর্ববর্তী এক্সেপশন।
- \`Data\`: কাস্টম কি/ভ্যালু পেয়ারের মেটাডেটা ডিকশনারি।

### ২. \`System.SystemException\`
CLR রানটাইম ইঞ্জিন কর্তৃক স্বয়ংক্রিয়ভাবে জেনারেট হওয়া সিস্টেম ত্রুটির বেস ক্লাস (যেমন: \`NullReferenceException\`, \`OutOfMemoryException\`, \`StackOverflowException\`)।

### ৩. \`System.ApplicationException\` (বাতিল হওয়া আর্কিটেকচারাল প্যাটার্ন)
- **প্রাথমিক পরিকল্পনা (.NET 1.0)**: মাইক্রোসফটের পরিকল্পনা ছিল ফ্রেমওয়ার্কের ত্রুটিগুলো \`SystemException\` থেকে আসবে এবং অ্যাপ্লিকেশন কোডের ত্রুটিগুলো \`ApplicationException\` থেকে ইনহেরিট করবে।
- **ব্যর্থতার কারণ**: BCL টিম নিজেরাই এই নিয়ম ভঙ্গ করে অ্যাপ্লিকেশন এপিআই থেকে \`SystemException\` থ্রো করতে শুরু করে। ফলে এটি ফ্রেমওয়ার্ক ও অ্যাপ্লিকেশন এরর আলাদা করার উদ্দেশ্য পূরণ করতে পারেনি।
- **আধুনিক মানদণ্ড**: **কখনই \`ApplicationException\` থেকে ইনহেরিট করবেন না**, এবং এটি ক্যাচও করবেন না। সরাসরি \`System.Exception\` থেকে ইনহেরিট করে কাস্টম এক্সেপশন তৈরি করুন।

---

## স্ট্যান্ডার্ড BCL এক্সেপশন নির্বাচন গাইড

সঠিক BCL এক্সেপশন নির্বাচন কোডের উদ্দেশ্য স্পষ্ট করে এবং বাগ শনাক্তকরণ সহজ করে:

| এক্সেপশনের নাম | কখন ব্যবহার করবেন | আধুনিক গার্ড সিনট্যাক্স |
| :--- | :--- | :--- |
| **\`ArgumentNullException\`** | মেথডের কোনো প্যারামিটার \`null\` হওয়া নিষিদ্ধ কিন্তু \`null\` পাস করা হয়েছে। | \`ArgumentNullException.ThrowIfNull(arg);\` |
| **\`ArgumentOutOfRangeException\`** | প্যারামিটারের মান অনুমোদিত রেঞ্জ বা সীমার বাইরে (যেমন ঋণাত্মক ইনডেক্স)। | \`ArgumentOutOfRangeException.ThrowIfNegative(index);\` |
| **\`ArgumentException\`** | নাল বা রেঞ্জ ছাড়া অন্যান্য কারণে আর্গুমেন্ট অবৈধ হলে (যেমন ফাঁকা স্ট্রিং)। | \`throw new ArgumentException("String cannot be empty.", nameof(name));\` |
| **\`InvalidOperationException\`** | আর্গুমেন্ট সঠিক কিন্তু অবজেক্টের বর্তমান স্টেটের কারণে অপারেশন অবৈধ হলে। | বন্ধ কানেকশন বা স্ট্রিমে রিড/রাইট করার চেষ্টার ক্ষেত্রে। |
| **\`NotSupportedException\`** | কোনো ক্লাসে নির্দিষ্ট মেথডটি ডিজাইনগতভাবেই সমর্থিত নয়। | রিড-অনলি কালেকশনে \`.Add()\` কল করলে। |
| **\`NotImplementedException\`** | মেথডটির সিগনেচার তৈরি করা হয়েছে কিন্তু কোড এখনও লেখা হয়নি। | ডেভেলপমেন্ট স্টেজে ইন্টারফেস স্টাব তৈরির জন্য। |
| **\`OperationCanceledException\`** | \`CancellationToken\` এর মাধ্যমে অ্যাসিনক্রোনাস কাজ বাতিল করা হলে। | \`cancellationToken.ThrowIfCancellationRequested();\` |
| **\`KeyNotFoundException\`** | ডিকশনারিতে অনুপস্থিত কোনো কি (key) ইনডেক্সার দিয়ে খোঁজা হলে। | এক্সেপশন এড়াতে \`dict.TryGetValue(key, out var val)\` ব্যবহার করুন। |

---

## এক্সেপশন ফিল্টার (\`when\` ক্লজ)

সি# ৬ সংস্করণে \`catch\` ব্লকের সাথে শর্ত জুড়ে দেওয়ার জন্য \`when\` কি-ওয়ার্ড বা **Exception Filter** যুক্ত হয়:

\`\`\`csharp
catch (HttpRequestException ex) when (ex.StatusCode == HttpStatusCode.NotFound)
{
    Console.WriteLine("রিসোর্সটি খুঁজে পাওয়া যায়নি (404)!");
}
\`\`\`

### আন্ডার দ্য হুড: CLR Two-Pass এক্সেপশন হ্যান্ডলিং মডেল
উইন্ডোজ Structured Exception Handling (SEH) এর ওপর ভিত্তি করে CLR **দুটি পর্যায়ে** এক্সেপশন প্রসেস করে:

1. **Pass 1: Search Pass (স্ট্যাক ওয়াক)**:
   - কোনো মেথডে এক্সেপশন ঘটলে CLR কল স্ট্যাক বেয়ে উপরে উঠতে থাকে এবং উপযুক্ত \`catch\` ব্লক খোঁজে।
   - যদি কোনো \`catch\` ব্লকে \`when (condition)\` ফিল্টার থাকে, **CLR এই প্রথম পর্যায়েই শর্তটি মূল্যায়ন করে**!
   - **সবচেয়ে গুরুত্বপূর্ণ বিষয়**: এই সময়ে কল স্ট্যাক **আনওয়াইন্ড (Unwind) হয় না**! অর্থাৎ throw হওয়ার স্থান থেকে ক্যাচ মেথড পর্যন্ত প্রতিটি স্ট্যাক ফ্রেম, লোকাল ভ্যারিয়েবল ও মেমোরি স্টেট সম্পূর্ণ অক্ষত থাকে!
2. **Pass 2: Unwind Pass**:
   - যখন কোনো ক্যাচ ব্লকের ফিল্টার \`true\` রিটার্ন করে, কেবল তখনই CLR throw এর স্থান থেকে সেই ক্যাচ পর্যন্ত স্ট্যাক আনওয়াইন্ড করে এবং পথিমধ্যে থাকা \`finally\` ব্লকগুলো সম্পন্ন করে ক্যাচ ব্লকের মূল কোডে প্রবেশ করে।

---

## \`catch ... when\` বনাম \`catch ... { if (...) throw; }\` এর পার্থক্য

এক্সেপশন ফিল্টার ও সাধারণ \`if ... throw\` এর মধ্যে বিশাল আর্কিটেকচারাল পার্থক্য রয়েছে:

| বৈশিষ্ট্য | \`catch (Exception ex) when (cond)\` | \`catch (Exception ex) { if (!cond) throw; }\` |
| :--- | :--- | :--- |
| **স্ট্যাক আনওয়াইন্ডিং** | স্ট্যাক আনওয়াইন্ড হওয়ার **আগেই** শর্ত যাচাই হয়। | ক্যাচ ব্লকে প্রবেশের সাথে সাথে স্ট্যাক ইতিমধ্যে আনওয়াইন্ড হয়ে যায়। |
| **ক্র্যাশ ডাম্প ও ডিবাগিং** | মেমোরি ডাম্পে মূল এরর পয়েন্টের সকল লোকাল ভ্যারিয়েবল ও ফ্রেম অক্ষত থাকে। | মধ্যবর্তী ফ্রেম ও লোকাল ভ্যারিয়েবল ধ্বংস হয়ে যায়। |
| **\`finally\` এক্সিকিউশন** | ফিল্টার \`false\` হলে মধ্যবর্তী \`finally\` ব্লকগুলো চালানো হয় না। | মধ্যবর্তী \`finally\` ব্লকগুলো সময়ের আগেই সম্পন্ন হয়ে যায়! |
| **পারফরম্যান্স** | ফিল্টার অসত্য হলে আনওয়াইন্ডিংয়ের বিশাল ওভারহেড সম্পূর্ণ এড়িয়ে যায়। | আনওয়াইন্ড ও রি-থ্রো করার অপচয় ঘটে। |

\`\`\`csharp
// ক্ষতিকর প্র্যাকটিস: স্ট্যাক নষ্ট করে এবং ডায়াগনস্টিক তথ্য মুছে দেয়
try
{
    ExecuteExternalOperation();
}
catch (SqlException ex)
{
    if (ex.Number != 1205) // ডেডলক না হলে
    {
        throw; // কিন্তু স্ট্যাক ইতিমধ্যে আনওয়াইন্ড হয়ে গেছে!
    }
    HandleDeadlock(ex);
}

// আধুনিক সঠিক প্র্যাকটিস: ডেডলক না হলে কোনো স্ট্যাক আনওয়াইন্ড হবে না!
try
{
    ExecuteExternalOperation();
}
catch (SqlException ex) when (ex.Number == 1205)
{
    HandleDeadlock(ex);
}
\`\`\`

---

## "Log Without Catching" প্যাটার্ন

যেহেতু ফিল্টার কন্ডিশন প্রথম পর্যায়েই কল স্ট্যাক আনওয়াইন্ড না করে চলে, তাই এমন একটি মেথড কল করা যায় যা লগ তৈরি করে সবসময় \`false\` রিটার্ন করবে:

\`\`\`csharp
public static bool LogException(Exception ex)
{
    Logger.LogError(ex, "প্রথম পাসে ত্রুটির সম্পূর্ণ স্ট্যাক ট্রেস লগ করা হলো।");
    return false; // false রিটার্ন করায় CLR পরবর্তী হ্যান্ডলার খুঁজতে থাকবে!
}

// মূল অ্যাপ্লিকেশনে:
try
{
    ProcessOrderPipeline();
}
catch (Exception ex) when (LogException(ex))
{
    // এই ব্লকে কখনও প্রবেশ করবে না কারণ ফিল্টার সবসময় false দেয়!
}
\`\`\`

---

## সম্পূর্ণ ব্যবহারিক কোড: রেজিলিয়েন্স ও এরর ডিসক্রিমিনেশন

\`\`\`csharp
using System;
using System.Net;
using System.Net.Http;

public class ResilienceHandler
{
    public static void ExecuteWithFilter(int simulatedHttpCode)
    {
        try
        {
            SimulateRemoteCall(simulatedHttpCode);
        }
        catch (HttpRequestException ex) when (ex.StatusCode == HttpStatusCode.RequestTimeout || 
                                              ex.StatusCode == HttpStatusCode.GatewayTimeout)
        {
            Console.WriteLine($"[Transient Timeout] {ex.StatusCode}: Retrying operation...");
        }
        catch (HttpRequestException ex) when (ex.StatusCode == HttpStatusCode.NotFound)
        {
            Console.WriteLine("[Resource Missing] 404 Not Found: Entity does not exist.");
        }
        catch (HttpRequestException ex) when ((int)ex.StatusCode! >= 500 && (int)ex.StatusCode <= 599)
        {
            Console.WriteLine($"[Server Fault] Critical upstream error: {ex.StatusCode}");
        }
        catch (Exception ex) when (LogUncaughtException(ex))
        {
            // Logging interceptor (never entered)
        }
    }

    private static bool LogUncaughtException(Exception ex)
    {
        Console.WriteLine($"[Audit Log] Intercepted {ex.GetType().Name} before unwind: {ex.Message}");
        return false;
    }

    private static void SimulateRemoteCall(int code)
    {
        throw new HttpRequestException($"HTTP {(HttpStatusCode)code}", null, (HttpStatusCode)code);
    }

    public static void Main()
    {
        ExecuteWithFilter(404);
        ExecuteWithFilter(504);
        ExecuteWithFilter(500);
    }
}
\`\`\`

---

## বাস্তব সমস্যা সমাধান ও বিস্তারিত বিশ্লেষণ

### সমস্যা: Codeforces Assiut Sheet #1 Problem U (Float or int)
*একটি বাস্তব সংখ্যা $N$ দেওয়া থাকবে। এটি পূর্ণসংখ্যা (integer) নাকি দশমিক ভগ্নাংশ (float) তা নির্ধারণ করতে হবে। পূর্ণসংখ্যা হলে \`int {integer_part}\` এবং ভগ্নাংশ হলে \`float {integer_part} {fractional_part}\` প্রিন্ট করুন।*

#### সমস্যা বিশ্লেষণ
১. ইনপুট ফরম্যাট: দশমিক সংখ্যা নির্দেশক স্ট্রিং (যেমন: \`234.000\` অথবা \`534.958\`)।
২. ধরন নির্ধারণ:
   - স্ট্রিংটিকে \`.\` এর সাপেক্ষে বিভক্ত করুন।
   - দশমিকের পরের অংশ শূন্যের সমান হলে এটি পূর্ণসংখ্যা।
   - অন্যথায় এটি ফ্লোট সংখ্যা হিসেবে পরিগণিত হবে।
৩. এক্সেপশন গার্ড: ফরম্যাট কনভার্সন সুরক্ষিত রাখতে ফরম্যাট এক্সেপশন হ্যান্ডলিং নিশ্চিত করা।

#### C# সমাধান

\`\`\`csharp
using System;
using System.Globalization;

public class Program
{
    public static void Main()
    {
        string? input = Console.ReadLine();
        if (string.IsNullOrWhiteSpace(input))
        {
            return;
        }

        try
        {
            ClassifyNumber(input.Trim());
        }
        catch (FormatException ex)
        {
            Console.WriteLine($"[Input Error] Failed to parse input: {ex.Message}");
        }
    }

    public static void ClassifyNumber(string value)
    {
        int dotIndex = value.IndexOf('.');

        if (dotIndex == -1)
        {
            Console.WriteLine($"int {value}");
            return;
        }

        string integerPartStr = value.Substring(0, dotIndex);
        string fractionalPartStr = value.Substring(dotIndex + 1);

        // Parse fraction to inspect if it contains non-zero value
        if (double.TryParse("0." + fractionalPartStr, NumberStyles.Float, CultureInfo.InvariantCulture, out double fractionVal))
        {
            if (fractionVal == 0.0)
            {
                Console.WriteLine($"int {integerPartStr}");
            }
            else
            {
                Console.WriteLine($"float {integerPartStr} 0.{fractionalPartStr}");
            }
        }
        else
        {
            throw new FormatException($"Invalid numeric format in fraction: {fractionalPartStr}");
        }
    }
}
\`\`\`

#### জটিলতা বিশ্লেষণ
- **টাইম কমপ্লেক্সিটি**: $\\mathcal{O}(L)$, যেখানে $L$ হলো ইনপুট স্ট্রিংটির দৈর্ঘ্য ($L \\le 100$)। ডট খোঁজা এবং সাবস্ট্রিং তৈরিতে ইনপুট দৈর্ঘ্যের সমান সময় লাগে।
- **স্পেস কমপ্লেক্সিটি**: $\\mathcal{O}(L)$, পূর্ণসংখ্যা ও ভগ্নাংশের নতুন সাবস্ট্রিং অ্যালোকেশনের জন্য।

---

## অনুশীলনের জন্য নির্বাচিত সমস্যা

| স্ট্যাটাস | সোর্স | সমস্যার নাম | কাঠিন্য | মূল ধারণা |
| :---: | :--- | :--- | :--- | :--- |
| ⚪ | Codeforces | [Assiut Sheet #1: Float or int](https://codeforces.com/group/MWSDmqGsZm/contest/219158/problem/U) | Easy | Number parsing, String discrimination, Guard clauses |
| ⚪ | Codeforces | [Assiut Sheet #1: Comparison](https://codeforces.com/group/MWSDmqGsZm/contest/219158/problem/V) | Easy | Conditional branches, Relational evaluation, Input validation |
| ⚪ | Exercism C# | [Attack of the Trolls](https://exercism.org/tracks/csharp/exercises/attack-of-the-trolls) | Medium | Exception filters (\`when\`), Role permission checking |
| ⚪ | Exercism C# | [Calculator Conundrum](https://exercism.org/tracks/csharp/exercises/calculator-conundrum) | Medium | BCL exception hierarchy, ArgumentNullException, InvalidOperationException |
`,
  resources: [],
  problems: [
    {
      source: "Codeforces",
      name: "Assiut Sheet #1: Float or int",
      url: "https://codeforces.com/group/MWSDmqGsZm/contest/219158/problem/U",
      difficulty: "EASY",
      company: "Therap Services",
      tags: ["Type System", "Parsing", "Guards"],
      solutionEn:
        "Parse the numeric string around the decimal delimiter. Inspect whether the fractional decimal value equals zero to classify as an integer or float, guarding format conversions with FormatException handlers.",
      solutionBn:
        "দশমিক চিহ্নের ওপর ভিত্তি করে স্ট্রিং বিভক্ত করুন। ভগ্নাংশের মান শূন্য কি না তা যাচাই করে int অথবা float নির্ধারণ করুন এবং ফরম্যাট রূপান্তরটি FormatException দিয়ে সুরক্ষিত রাখুন।",
    },
    {
      source: "Codeforces",
      name: "Assiut Sheet #1: Comparison",
      url: "https://codeforces.com/group/MWSDmqGsZm/contest/219158/problem/V",
      difficulty: "EASY",
      company: "Brain Station 23",
      tags: ["Logic", "Comparison", "Exception Guards"],
      solutionEn:
        "Parse expressions containing relational operators (<, >, =) and evaluate correctness, throwing and handling ArgumentException if an unrecognized operator is supplied.",
      solutionBn:
        "রিলেশনাল অপারেটর (<, >, =) পার্স করে অভিব্যক্তিটির সত্যতা যাচাই করুন এবং অবৈধ অপারেটর শনাক্ত করতে ArgumentException ব্যবহার করুন।",
    },
    {
      source: "Exercism C#",
      name: "Attack of the Trolls",
      url: "https://exercism.org/tracks/csharp/exercises/attack-of-the-trolls",
      difficulty: "MEDIUM",
      company: "Enosis Solutions",
      tags: ["Exceptions", "Hierarchy", "Filters"],
      solutionEn:
        "Implement fine-grained role-based permission checking using exception filters with when clauses to selectively handle access violations without unwinding the stack.",
      solutionBn:
        "when ক্লজ সমন্বিত এক্সেপশন ফিল্টার ব্যবহার করে কল স্ট্যাক আনওয়াইন্ড না করেই নির্দিষ্ট পারমিশন ভায়োলেশন সুন্দরভাবে হ্যান্ডেল করুন।",
    },
    {
      source: "Exercism C#",
      name: "Calculator Conundrum",
      url: "https://exercism.org/tracks/csharp/exercises/calculator-conundrum",
      difficulty: "MEDIUM",
      company: "Samsung R&D Institute Bangladesh",
      tags: ["Exception Hierarchy", "ArgumentException", "InvalidOperationException"],
      solutionEn:
        "Discriminate between null arguments, unsupported operators, and division by zero using standard BCL exception hierarchy (ArgumentNullException, ArgumentOutOfRangeException, DivideByZeroException).",
      solutionBn:
        "স্ট্যান্ডার্ড BCL এক্সেপশন হায়ারার্কি ব্যবহার করে নাল আর্গুমেন্ট, অনির্ধারিত অপারেটর এবং শূন্য দিয়ে ভাগের ক্ষেত্রে সঠিক এক্সেপশন টাইপ ডিসপ্যাচ ও ফিল্টার করুন।",
    },
  ],
};
