import type { LocalLesson } from "@/lib/lessons-data";

export const iteratorsYieldLesson: LocalLesson = {
  slug: "iterators-yield",
  titleEn: "yield return & yield break",
  titleBn: "ইল্ড (yield return ও yield break) স্টেট মেশিন",
  categoryEn: "14. Iterators",
  categoryBn: "১৪. আইটারেটর ও ইল্ড (Iterators & yield)",
  categoryDescEn:
    "Sequence iteration in C#: IEnumerable, IEnumerator state machines, lazy generation with yield return, and memory management.",
  categoryDescBn:
    "সি# এ আইটারেশন মেকানিজম: IEnumerable, IEnumerator স্টেট মেশিন, yield return দিয়ে অলস ডেটা জেনারেশন ও মেমোরি নিয়ন্ত্রণ।",
  categoryPriority: "CORE",
  descriptionEn:
    "Compiler-generated state machine lowering, try-finally disposal guarantees, argument validation patterns, infinite streams, and yield break.",
  descriptionBn:
    "কম্পাইলার-জেনারেটেড স্টেট মেশিন, try-finally ডিসপোজাল গ্যারান্টি, আর্গুমেন্ট ভ্যালিডেশন প্যাটার্ন, ইনফিনিট স্ট্রিম ও yield break।",
  difficulty: "MEDIUM",
  displayOrder: 3,
  prerequisites: ["iterators-ienumerator"],
  estimatedMinutes: 25,
  lastUpdated: "Recently updated",
  contentEn: `# yield return & yield break in C#

The **\`yield\`** contextual keyword instructs the Roslyn C# compiler to transform an ordinary method into an **iterator block**. Rather than executing continuously, the method transforms into a state machine that pauses and resumes on demand.

---

## Under the Hood: Roslyn State Machine Lowering

When you write a method containing \`yield return\`:

\`\`\`csharp
public static IEnumerable<int> CountUpTo(int limit)
{
    for (int i = 1; i <= limit; i++)
    {
        yield return i;
    }
}
\`\`\`

The C# compiler does **not** compile this into a normal subroutine. Instead, it generates a hidden private class implementing \`IEnumerable<int>\`, \`IEnumerator<int>\`, and \`IDisposable\`:

\`\`\`csharp
// Conceptual code generated by Roslyn compiler
[CompilerGenerated]
private sealed class <CountUpTo>d__0 : IEnumerable<int>, IEnumerator<int>
{
    private int <>1__state; // -1: unstarted, 0: running, -2: disposed
    private int <>2__current;
    public int limit;
    private int <i>5__1; // Local variable hoisted to a class field!

    public bool MoveNext()
    {
        switch (<>1__state)
        {
            case 0:
                <>1__state = -1;
                <i>5__1 = 1;
                break;
            case 1:
                <>1__state = -1;
                <i>5__1++;
                break;
            default:
                return false;
        }

        if (<i>5__1 <= limit)
        {
            <>2__current = <i>5__1;
            <>1__state = 1; // State saved: resumes here next time!
            return true;
        }

        return false;
    }
}
\`\`\`

### Execution Suspension:
- When \`yield return\` is hit, the current state and hoisted local variables are frozen on the heap.
- The method yields control back to the caller.
- On the next \`MoveNext()\` invocation, execution resumes **at the exact line following the \`yield return\`** statement.

---

## Early Termination with yield break

The **\`yield break\`** statement signals that the sequence has completed, immediately exiting the iterator and setting \`MoveNext()\` to \`false\`:

\`\`\`csharp
public static IEnumerable<int> TakeWhilePositive(IEnumerable<int> numbers)
{
    foreach (int n in numbers)
    {
        if (n <= 0)
        {
            yield break; // Cleanly terminates the iterator
        }
        yield return n;
    }
}
\`\`\`

---

## The try-finally Disposal Guarantee

One of the most important guarantees of C# iterator blocks is how they interact with \`finally\` blocks:

> **Guaranteed Cleanup**: Even if the consumer exits a \`foreach\` loop early via \`break\`, \`return\`, or an unhandled exception, the compiler-generated \`Dispose()\` method ensures that the \`finally\` block **is guaranteed to execute**!

\`\`\`csharp
public static IEnumerable<string> ReadLines(string path)
{
    StreamReader reader = new(path);
    try
    {
        while (!reader.EndOfStream)
        {
            yield return reader.ReadLine()!;
        }
    }
    finally
    {
        // GUARANTEED to execute even if the consumer breaks after 1 line!
        reader.Dispose();
        Console.WriteLine("File handle cleanly released.");
    }
}

// Consumer usage:
foreach (string line in ReadLines("data.txt"))
{
    if (line.StartsWith("TARGET")) 
    {
        break; // finally block runs immediately when foreach disposes the enumerator!
    }
}
\`\`\`

### Compiler Restrictions on Yield:
- \`yield return\` cannot appear inside a \`catch\` block.
- \`yield return\` cannot appear inside a \`finally\` block.
- \`yield return\` cannot appear inside a \`try\` block that has a \`catch\` handler (only \`try-finally\` is allowed).

---

## The Iterator Method Argument Validation Pattern

A classic bug in .NET occurs when validating arguments inside an iterator block:

\`\`\`csharp
// FATAL FLAW: ArgumentNullException is NOT thrown when the method is called!
public static IEnumerable<T> FilterBad<T>(IEnumerable<T> source)
{
    if (source == null) throw new ArgumentNullException(nameof(source)); // Deferred!
    foreach (var item in source) yield return item;
}

// The caller:
var query = FilterBad<int>(null); // NO EXCEPTION THROWN HERE!
// Exception only throws later when someone calls foreach or ToList()!
\`\`\`

### The Solution: Public Eager Validator + Private Lazy Iterator
\`\`\`csharp
public static IEnumerable<T> FilterGood<T>(IEnumerable<T> source)
{
    // Eager validation: Throws immediately on invocation!
    if (source == null) throw new ArgumentNullException(nameof(source));

    return IteratorCore(source);

    // Private local function runs lazily
    static IEnumerable<T> IteratorCore(IEnumerable<T> source)
    {
        foreach (var item in source)
        {
            yield return item;
        }
    }
}
\`\`\`

---

## Modeling Infinite Sequences in O(1) Memory

Because \`yield return\` evaluates on demand, it can model infinite mathematical sequences without exhausting system memory:

\`\`\`csharp
public static IEnumerable<long> Fibonacci()
{
    long a = 0, b = 1;
    while (true)
    {
        yield return a;
        long next = a + b;
        a = b;
        b = next;
    }
}

// Consumes only the first 10 numbers in O(1) auxiliary memory:
var first10 = Fibonacci().Take(10).ToList();
\`\`\`

---

## Practical Problem Walkthrough

### Problem: Codeforces Assiut Sheet #2 Problem C (Even, Odd, Positive and Negative)
*Given $N$ numbers. Count how many of these numbers are Even, Odd, Positive, and Negative.*

#### Algorithmic Analysis
1. Read the number count $N$ and the sequence of integers.
2. Filter classification categories using an iterator pipeline.
3. Zero is neither positive nor negative, but is considered even.

#### C# Implementation

\`\`\`csharp
using System;
using System.Collections.Generic;

public class Program
{
    public static void Main()
    {
        string? nLine = Console.ReadLine();
        if (string.IsNullOrWhiteSpace(nLine)) return;

        string? numbersLine = Console.ReadLine();
        if (string.IsNullOrWhiteSpace(numbersLine)) return;

        string[] tokens = numbersLine.Trim().Split(' ', StringSplitOptions.RemoveEmptyEntries);

        int evens = 0;
        int odds = 0;
        int positives = 0;
        int negatives = 0;

        foreach (int val in ParseTokens(tokens))
        {
            if ((val & 1) == 0) evens++;
            else odds++;

            if (val > 0) positives++;
            else if (val < 0) negatives++;
        }

        Console.WriteLine($"Even: {evens}");
        Console.WriteLine($"Odd: {odds}");
        Console.WriteLine($"Positive: {positives}");
        Console.WriteLine($"Negative: {negatives}");
    }

    // Lazy streaming parser using yield return
    private static IEnumerable<int> ParseTokens(string[] tokens)
    {
        foreach (string token in tokens)
        {
            if (int.TryParse(token, out int parsed))
            {
                yield return parsed;
            }
        }
    }
}
\`\`\`

#### Complexity Analysis
- **Time Complexity**: $\\mathcal{O}(N)$, streaming through $N$ integers in a single pass.
- **Space Complexity**: $\\mathcal{O}(1)$ auxiliary memory for the iterator state machine.

---

## Recommended Practice Problems

| Status | Source | Problem Name | Difficulty | Focus Concepts |
| :---: | :--- | :--- | :--- | :--- |
| ⚪ | Codeforces | [Assiut Sheet #2: Even, Odd, Positive, Negative](https://codeforces.com/group/MWSDmqGsZm/contest/219432/problem/C) | Easy | Streaming classification, \`yield return\` |
| ⚪ | Codeforces | [Assiut Sheet #2: Digits](https://codeforces.com/group/MWSDmqGsZm/contest/219432/problem/Q) | Easy | Digit decomposition iterator, Modulo |
| ⚪ | Exercism C# | [Raindrops](https://exercism.org/tracks/csharp/exercises/raindrops) | Easy | Sequence generation, String formatting |
| ⚪ | Exercism C# | [Meetup](https://exercism.org/tracks/csharp/exercises/meetup) | Medium | Date iteration, Calendar day streaming |
`,

  contentBn: `# C# এ ইল্ড (yield return ও yield break) স্টেট মেশিন

C#-এ **\`yield\`** কিওয়ার্ডটি Roslyn কম্পাইলারকে নির্দেশ দেয় যে সাধারণ মেথডটিকে একটি **আইটারেটর ব্লক (Iterator Block)** হিসেবে রূপান্তর করতে হবে। মেথডটি একবারে সম্পূর্ণ এক্সিকিউট না হয়ে একটি স্টেট মেশিনে রূপান্তরিত হয় যা চাহিদা অনুযায়ী থামে এবং পুনরায় শুরু হয়।

---

## আন্ডার দ্য হুড: কম্পাইলার স্টেট মেশিন রূপান্তর (Lowering)

যখন আমরা একটি মেথডে \`yield return\` লিখি:

\`\`\`csharp
public static IEnumerable<int> CountUpTo(int limit)
{
    for (int i = 1; i <= limit; i++)
    {
        yield return i;
    }
}
\`\`\`

কম্পাইলার এটিকে কোনো সাধারণ সাবরুটিন হিসেবে রাখে না। বরং এটি গোপনে একটি প্রাইভেট ক্লাস তৈরি করে যা \`IEnumerable<int>\`, \`IEnumerator<int>\` এবং \`IDisposable\` ইমপ্লিমেন্ট করে:

\`\`\`csharp
// Roslyn কম্পাইলারের তৈরি ধারণাগত অভ্যন্তরীণ কোড
[CompilerGenerated]
private sealed class <CountUpTo>d__0 : IEnumerable<int>, IEnumerator<int>
{
    private int <>1__state; // -1: শুরু হয়নি, 0: রানিং, 1: স্থগিত, -2: ডিসপোজড
    private int <>2__current;
    public int limit;
    private int <i>5__1; // লোকাল ভেরিয়েবল ক্লাসের ফিল্ডে পরিণত হয়!

    public bool MoveNext()
    {
        switch (<>1__state)
        {
            case 0:
                <>1__state = -1;
                <i>5__1 = 1;
                break;
            case 1:
                <>1__state = -1;
                <i>5__1++;
                break;
            default:
                return false;
        }

        if (<i>5__1 <= limit)
        {
            <>2__current = <i>5__1;
            <>1__state = 1; // বর্তমান স্টেট সেভ হলো: পরের বার এখান থেকেই শুরু হবে!
            return true;
        }

        return false;
    }
}
\`\`\`

### এক্সিকিউশন স্থগিতকরণ:
- যখন কোড \`yield return\` লাইনে পৌঁছায়, বর্তমান লোকাল ভেরিয়েবলের মান এবং প্রোগ্রামের এক্সিকিউশন স্টেট হিপে ফ্রোজেন (Frozen) হয়ে যায়।
- মেথডটি কলারের কাছে মান ফেরত পাঠায়।
- পরবর্তী \`MoveNext()\` কল করার সাথে সাথে মেথডটি **ঠিক সেই \`yield return\` লাইনের পর থেকে** পুনরায় চলা শুরু করে।

---

## yield break দিয়ে আগাম সমাপ্তি

**\`yield break\`** স্টেটমেন্টের মাধ্যমে আইটারেশন তাৎক্ষণিকভাবে সমাপ্ত করা যায়, যার ফলে \`MoveNext()\` সরাসরি \`false\` রিটার্ন করে:

\`\`\`csharp
public static IEnumerable<int> TakeWhilePositive(IEnumerable<int> numbers)
{
    foreach (int n in numbers)
    {
        if (n <= 0)
        {
            yield break; // আইটারেটর অবিলম্বে বন্ধ হয়ে যাবে
        }
        yield return n;
    }
}
\`\`\`

---

## try-finally ব্লকের ডিসপোজাল নিশ্চয়তা

C# আইটারেটরের অন্যতম চমৎকার বৈশিষ্ট্য হলো \`finally\` ব্লকের সাথে এর আচরণ:

> **গ্যারান্টিযুক্ত ক্লিনআপ**: কলার যদি \`foreach\` লুপের মাঝপথে \`break\` দিয়ে বের হয়ে যায় বা কোনো এক্সেপশন ঘটে, তবুও কম্পাইলারের তৈরি \`Dispose()\` মেথডের কারণে \`finally\` ব্লক **অবশ্যই এক্সিকিউট হবে**!

\`\`\`csharp
public static IEnumerable<string> ReadLines(string path)
{
    StreamReader reader = new(path);
    try
    {
        while (!reader.EndOfStream)
        {
            yield return reader.ReadLine()!;
        }
    }
    finally
    {
        // কলার মাঝপথে break করলেও এই ব্লকটি অবশ্যই এক্সিকিউট হবে!
        reader.Dispose();
        Console.WriteLine("File handle cleanly released.");
    }
}

// কলার ব্যবহার:
foreach (string line in ReadLines("data.txt"))
{
    if (line.StartsWith("TARGET")) 
    {
        break; // break করার সাথে সাথে finally ব্লকটি কার্যকর হয়!
    }
}
\`\`\`

### কম্পাইলারের সীমাবদ্ধতা:
- \`yield return\` কোনো \`catch\` ব্লকের ভেতরে লেখা যায় না।
- \`yield return\` কোনো \`finally\` ব্লকের ভেতরে লেখা যায় না।
- \`yield return\` কোনো \`try-catch\` ব্লকের \`try\` এর ভেতরে লেখা যায় না (কেবলমাত্র \`try-finally\` অনুমোদিত)।

---

## আর্গুমেন্ট ভ্যালিডেশন প্যাটার্ন (Argument Validation Trap)

একটি বড় বাগ ঘটে যখন আইটারেটর মেথডের শুরুতে প্যারামিটার ভ্যালিডেশন করা হয়:

\`\`\`csharp
// মারাত্মক ভুল: মেথড কল করার সময় ArgumentNullException ছুড়বে না!
public static IEnumerable<T> FilterBad<T>(IEnumerable<T> source)
{
    if (source == null) throw new ArgumentNullException(nameof(source)); // ডিফার্ড!
    foreach (var item in source) yield return item;
}

// কলার:
var query = FilterBad<int>(null); // এখানে কোনো এক্সেপশন হবে না!
// পরবর্তীতে যখন কেউ foreach চালাবে কেবল তখনই এক্সেপশন ঘটবে!
\`\`\`

### সমাধান: পাবলিক ইগার ভ্যালিডেটর + প্রাইভেট লোকাল ফাংশন
\`\`\`csharp
public static IEnumerable<T> FilterGood<T>(IEnumerable<T> source)
{
    // তাৎক্ষণিক ভ্যালিডেশন: মেথড কলের মুহূর্তেই এক্সেপশন দেবে
    if (source == null) throw new ArgumentNullException(nameof(source));

    return IteratorCore(source);

    static IEnumerable<T> IteratorCore(IEnumerable<T> source)
    {
        foreach (var item in source)
        {
            yield return item;
        }
    }
}
\`\`\`

---

## অসীম সিকোয়েন্স ও O(1) মেমোরি মডেলিং

যেহেতু \`yield return\` চাহিদা অনুযায়ী মান তৈরি করে, তাই মেমোরি খরচ না করেই গাণিতিক অসীম ধারা মডেল করা যায়:

\`\`\`csharp
public static IEnumerable<long> Fibonacci()
{
    long a = 0, b = 1;
    while (true)
    {
        yield return a;
        long next = a + b;
        a = b;
        b = next;
    }
}

// মেমরিতে মাত্র O(1) খরচে প্রথম ১০টি সংখ্যা গ্রহণ করা:
var first10 = Fibonacci().Take(10).ToList();
\`\`\`

---

## বাস্তব সমস্যা সমাধান ও বিস্তারিত বিশ্লেষণ

### সমস্যা: Codeforces Assiut Sheet #2 Problem C (Even, Odd, Positive and Negative)
*একটি সংখ্যা $N$ এবং $N$ সংখ্যক সংখ্যার একটি তালিকা দেওয়া থাকবে। কতটি সংখ্যা জোড়, বিজোড়, ধনাত্মক এবং ঋণাত্মক তা গণনা করুন।*

#### সমাধান বিশ্লেষণ
১. ইনপুট সংখ্যাগুলো রিড করা।
২. একটি লেজি স্ট্রিমিং পার্সারের সাহায্যে \`yield return\` দিয়ে সংখ্যাগুলো একটি একটি করে সরবরাহ করা।
৩. শূন্য ধনাত্মক বা ঋণাত্মক নয়, তবে জোড় সংখ্যা—এই শর্ত মেনে কাউন্ট আপডেট করা।

#### C# সমাধান

\`\`\`csharp
using System;
using System.Collections.Generic;

public class Program
{
    public static void Main()
    {
        string? nLine = Console.ReadLine();
        if (string.IsNullOrWhiteSpace(nLine)) return;

        string? numbersLine = Console.ReadLine();
        if (string.IsNullOrWhiteSpace(numbersLine)) return;

        string[] tokens = numbersLine.Trim().Split(' ', StringSplitOptions.RemoveEmptyEntries);

        int evens = 0;
        int odds = 0;
        int positives = 0;
        int negatives = 0;

        foreach (int val in ParseTokens(tokens))
        {
            if ((val & 1) == 0) evens++;
            else odds++;

            if (val > 0) positives++;
            else if (val < 0) negatives++;
        }

        Console.WriteLine($"Even: {evens}");
        Console.WriteLine($"Odd: {odds}");
        Console.WriteLine($"Positive: {positives}");
        Console.WriteLine($"Negative: {negatives}");
    }

    private static IEnumerable<int> ParseTokens(string[] tokens)
    {
        foreach (string token in tokens)
        {
            if (int.TryParse(token, out int parsed))
            {
                yield return parsed;
            }
        }
    }
}
\`\`\`

#### জটিলতা বিশ্লেষণ
- **টাইম কমপ্লেক্সিটি**: $\\mathcal{O}(N)$, একক পাসে $N$ সংখ্যক সংখ্যা প্রসেস করে।
- **স্পেস কমপ্লেক্সিটি**: স্টেট মেশিনের জন্য $\\mathcal{O}(1)$ অতিরিক্ত মেমোরি।

---

## অনুশীলনের জন্য নির্বাচিত সমস্যা

| স্ট্যাটাস | সোর্স | সমস্যার নাম | কাঠিন্য | মূল ধারণা |
| :---: | :--- | :--- | :--- | :--- |
| ⚪ | Codeforces | [Assiut Sheet #2: Even, Odd, Positive, Negative](https://codeforces.com/group/MWSDmqGsZm/contest/219432/problem/C) | Easy | Streaming classification, \`yield return\` |
| ⚪ | Codeforces | [Assiut Sheet #2: Digits](https://codeforces.com/group/MWSDmqGsZm/contest/219432/problem/Q) | Easy | Digit decomposition iterator, Modulo |
| ⚪ | Exercism C# | [Raindrops](https://exercism.org/tracks/csharp/exercises/raindrops) | Easy | Sequence generation, String formatting |
| ⚪ | Exercism C# | [Meetup](https://exercism.org/tracks/csharp/exercises/meetup) | Medium | Date iteration, Calendar day streaming |
`,
  resources: [],
  problems: [
    {
      source: "Codeforces",
      name: "Assiut Sheet #2: Even, Odd, Positive, Negative",
      url: "https://codeforces.com/group/MWSDmqGsZm/contest/219432/problem/C",
      difficulty: "EASY",
      company: "Brain Station 23",
      tags: ["Yield", "Parity", "Conditionals"],
      solutionEn:
        "Stream and classify integers into parity and sign buckets using a single-pass traversal.",
      solutionBn:
        "একক পাসে স্ট্রিমিং আইটারেশনের মাধ্যমে সংখ্যাগুলোকে জোড়, বিজোড়, ধনাত্মক ও ঋণাত্মক ক্যাটাগরিতে ভাগ করুন।",
    },
    {
      source: "Codeforces",
      name: "Assiut Sheet #2: Digits",
      url: "https://codeforces.com/group/MWSDmqGsZm/contest/219432/problem/Q",
      difficulty: "EASY",
      company: "Therap Services",
      tags: ["Yield", "Math", "Digits"],
      solutionEn:
        "Yield digits of an integer in reverse order using modulo 10 extraction and space-delimited formatting.",
      solutionBn:
        "মডিউলো 10 এর সাহায্যে পূর্ণসংখ্যার অঙ্কগুলো বিপরীত ক্রমে ইল্ড করে স্পেস দিয়ে প্রদর্শন করুন।",
    },
    {
      source: "Exercism C#",
      name: "Raindrops",
      url: "https://exercism.org/tracks/csharp/exercises/raindrops",
      difficulty: "EASY",
      company: "Enosis Solutions",
      tags: ["Yield", "Strings", "Factors"],
      solutionEn:
        "Convert a number to raindrop sounds based on its factors 3, 5, and 7 or emit the number as string.",
      solutionBn:
        "৩, ৫ ও ৭ গুণনীয়কের ওপর ভিত্তি করে সংখ্যাকে রেইনড্রপ শব্দে রূপান্তর করুন অথবা সংখ্যাটি অপরিবর্তিত রাখুন।",
    },
    {
      source: "Exercism C#",
      name: "Meetup",
      url: "https://exercism.org/tracks/csharp/exercises/meetup",
      difficulty: "MEDIUM",
      company: "BJIT Group",
      tags: ["Yield", "DateTime", "Calendar"],
      solutionEn:
        "Stream calendar days of a month to locate teenth, first, second, third, fourth, or last occurrences of days of the week.",
      solutionBn:
        "মাসের দিনগুলো স্ট্রিম করে সপ্তাহের নির্দিষ্ট দিনের teenth, প্রথম, দ্বিতীয় বা শেষ অবস্থান শনাক্ত করুন।",
    },
  ],
};
