import type { LocalLesson } from "@/lib/lessons-data";

export const iteratorsIenumerableLesson: LocalLesson = {
  slug: "iterators-ienumerable",
  titleEn: "IEnumerable vs IEnumerator",
  titleBn: "আই-ইনুমারেবল বনাম আই-ইনুমারেটর",
  categoryEn: "14. Iterators",
  categoryBn: "১৪. আইটারেটর ও ইল্ড (Iterators & yield)",
  categoryDescEn:
    "Sequence iteration in C#: IEnumerable, IEnumerator state machines, lazy generation with yield return, and memory management.",
  categoryDescBn:
    "সি# এ আইটারেশন মেকানিজম: IEnumerable, IEnumerator স্টেট মেশিন, yield return দিয়ে অলস ডেটা জেনারেশন ও মেমোরি নিয়ন্ত্রণ।",
  categoryPriority: "NORMAL",
  descriptionEn:
    "The producer-consumer iteration contract, foreach loop compiler lowering, pattern-based duck typing, and struct enumerator boxing prevention.",
  descriptionBn:
    "প্রোডিউসার-কনজিউমার আইটারেশন চুক্তি, foreach লুপের কম্পাইলার রূপান্তর, প্যাটার্ন-ভিত্তিক ডাক টাইপিং এবং স্ট্রাক্ট এনিউমারেটরের বক্সিং পরিহার।",
  difficulty: "EASY",
  displayOrder: 1,
  prerequisites: ["csharp-foreach-loop"],
  estimatedMinutes: 20,
  lastUpdated: "Recently updated",
  contentEn: `# IEnumerable vs IEnumerator in C#

In .NET, iterating through a sequence cleanly divides responsibilities between two foundational interfaces: **\`IEnumerable\`** (the sequence) and **\`IEnumerator\`** (the cursor).

Understanding this duality explains how \`foreach\` works under the hood, how high-performance collections avoid heap allocations, and why multiple enumerations can trigger unexpected behavior.

---

## The Book vs Bookmark Analogy

\`\`\`
  IEnumerable<T>  ─── "The Book" ─── Stateless, holds or generates the elements.
         │
         │ .GetEnumerator() creates a new cursor
         ▼
  IEnumerator<T>  ─── "The Bookmark" ─── Stateful, tracks current position & value.
\`\`\`

| Dimension | \`IEnumerable<T>\` | \`IEnumerator<T>\` |
| :--- | :--- | :--- |
| **Role** | The sequence to be traversed | The active cursor traversing the sequence |
| **Statefulness** | **Stateless** (can spawn multiple independent cursors) | **Stateful** (remembers its active position) |
| **Key Members** | \`IEnumerator<T> GetEnumerator()\` | \`bool MoveNext()\`, \`T Current { get; }\`, \`void Reset()\` |
| **Analogy** | A printed book on a shelf | A physical bookmark marking page 42 |
| **Concurrency** | Safe for multiple readers simultaneously | Inherently unsafe to share across threads |

---

## Foreach Loop Compiler Lowering

When you write a \`foreach\` loop, the C# compiler (Roslyn) translates (lowers) it into a \`while\` loop wrapped in a resource-safe \`try-finally\` block:

\`\`\`csharp
// Source code written by developer
foreach (string city in cities)
{
    Console.WriteLine(city);
}
\`\`\`

The compiler translates the above into:

\`\`\`csharp
// Lowered code generated by Roslyn compiler
IEnumerator<string> enumerator = cities.GetEnumerator();
try
{
    while (enumerator.MoveNext())
    {
        string city = enumerator.Current;
        Console.WriteLine(city);
    }
}
finally
{
    // Ensures unmanaged resources or file streams are closed immediately
    if (enumerator != null)
    {
        enumerator.Dispose();
    }
}
\`\`\`

---

## Pattern-Based Iteration (Duck Typing)

A remarkable design choice in C# is that a type **does NOT strictly need to implement \`IEnumerable\` or \`IEnumerator\`** to be used in a \`foreach\` loop!

The C# compiler uses **duck typing**. As long as a type satisfies the following pattern, \`foreach\` compiles successfully:
1. Contains a public method \`GetEnumerator()\` that returns an object/struct.
2. The returned enumerator contains a public \`bool MoveNext()\` method.
3. The returned enumerator contains a public \`Current\` property (read-only getter).

\`\`\`csharp
// Valid foreach target without implementing any interfaces!
public class DuckSequence
{
    public DuckEnumerator GetEnumerator() => new DuckEnumerator();
}

public ref struct DuckEnumerator
{
    private int _count;
    public bool MoveNext() => ++_count <= 3;
    public int Current => _count;
}

// Compiles and runs cleanly:
foreach (int val in new DuckSequence())
{
    Console.WriteLine(val); // Prints 1, 2, 3
}
\`\`\`

> **High-Performance Benefit**: \`Span<T>\` and \`ReadOnlySpan<T>\` rely on this exact pattern. Because they are \`ref struct\` types, they cannot implement interfaces (which would cause boxing). Duck typing allows them to work seamlessly with \`foreach\` at zero allocation cost!

---

## Struct Enumerators & The Boxing Penalty

Standard collections like \`List<T>\` return a **mutable value-type struct** from their \`GetEnumerator()\` method (\`List<T>.Enumerator\`):

\`\`\`csharp
List<int> numbers = new() { 1, 2, 3 };

// Zero Allocation: Uses the concrete List<T>.Enumerator struct directly on stack
foreach (int n in numbers) { ... }

// ALLOCATION PENALTY: Casting to IEnumerable<int> boxes the struct on the heap!
IEnumerable<int> boxed = numbers;
foreach (int n in boxed) { ... }
\`\`\`

When writing performance-critical algorithms, avoid casting collections to \`IEnumerable<T>\` in tight loops to prevent repetitive garbage collector allocations.

---

## Practical Problem Walkthrough

### Problem: Codeforces Assiut Sheet #3 Problem A (Summation)
*Given a number $N$ and an array $A$ of $N$ numbers. Print the absolute summation of these numbers.*

#### Algorithmic Analysis
1. Read the size $N$ and integer tokens into a 64-bit array to prevent 32-bit arithmetic overflow.
2. Traverse elements using an enumerator pattern, accumulating values into a running signed total.
3. Apply \`Math.Abs\` on the final 64-bit sum.

#### C# Implementation

\`\`\`csharp
using System;
using System.Collections.Generic;

public class Program
{
    public static void Main()
    {
        string? nLine = Console.ReadLine();
        if (string.IsNullOrWhiteSpace(nLine)) return;

        string? arrayLine = Console.ReadLine();
        if (string.IsNullOrWhiteSpace(arrayLine)) return;

        string[] tokens = arrayLine.Trim().Split(' ', StringSplitOptions.RemoveEmptyEntries);

        long totalSum = 0;

        // Using manual enumerator traversal
        IEnumerator<string> enumerator = ((IEnumerable<string>)tokens).GetEnumerator();
        try
        {
            while (enumerator.MoveNext())
            {
                if (long.TryParse(enumerator.Current, out long value))
                {
                    totalSum += value;
                }
            }
        }
        finally
        {
            enumerator.Dispose();
        }

        long absoluteSum = Math.Abs(totalSum);
        Console.WriteLine(absoluteSum);
    }
}
\`\`\`

#### Complexity Analysis
- **Time Complexity**: $\\mathcal{O}(N)$, scanning through $N$ tokens with constant-time accumulation.
- **Space Complexity**: $\\mathcal{O}(N)$ for token storage, while cursor traversal uses $\\mathcal{O}(1)$ memory.

---

## Recommended Practice Problems

| Status | Source | Problem Name | Difficulty | Focus Concepts |
| :---: | :--- | :--- | :--- | :--- |
| ⚪ | Codeforces | [Assiut Sheet #3: Summation](https://codeforces.com/group/MWSDmqGsZm/contest/219774/problem/A) | Easy | Accumulator traversal, 64-bit summation |
| ⚪ | Codeforces | [Assiut Sheet #3: Searching](https://codeforces.com/group/MWSDmqGsZm/contest/219774/problem/B) | Easy | Linear scan, Early exit cursor |
| ⚪ | Exercism C# | [Strain](https://exercism.org/tracks/csharp/exercises/strain) | Medium | Custom collection enumeration, \`IEnumerator\` |
| ⚪ | Exercism C# | [Custom Set](https://exercism.org/tracks/csharp/exercises/custom-set) | Medium | Implementing \`IEnumerable<T>\` from scratch |
`,

  contentBn: `# C# এ আই-ইনুমারেবল বনাম আই-ইনুমারেটর

.NET-এ কালেকশনের ওপর লুপ চালানোর দায়িত্বটি দুটি স্বতন্ত্র ইন্টারফেসে সুন্দরভাবে বিভক্ত: **\`IEnumerable\`** (সিকোয়েন্স বা কালেকশন) এবং **\`IEnumerator\`** (কার্সার বা নির্দেশক)।

এই আর্কিটেকচারাল বিভাজনটি বুঝতে পারলে \`foreach\` লুপ কীভাবে কাজ করে, উচ্চ-পারফরম্যান্সের কোডে কীভাবে হিপ মেমোরি বাঁচানো যায় এবং কেন একই কুয়েরি একাধিকবার চালালে অপ্রত্যাশিত সমস্যা হতে পারে তা পরিষ্কার হয়।

---

## বই বনাম বুকমার্কের তুলনা

\`\`\`
  IEnumerable<T>  ─── "বই (The Book)" ─── স্টেটলেস, উপাদান ধারণ বা তৈরি করে।
         │
         │ .GetEnumerator() একটি নতুন কার্সার তৈরি করে
         ▼
  IEnumerator<T>  ─── "বুকমার্ক (Bookmark)" ─── স্টেটফুল, বর্তমান পৃষ্ঠা ও মান মনে রাখে।
\`\`\`

| বৈশিষ্ট্য | \`IEnumerable<T>\` | \`IEnumerator<T>\` |
| :--- | :--- | :--- |
| **ভূমিকা** | যে কালেকশন বা সিকোয়েন্সের ওপর লুপ চলবে | লুপ চালানোর সময় বর্তমান পজিশন নির্দেশক কার্সার |
| **স্টেটফুলনেস** | **স্টেটলেস** (একাধিক স্বাধীন কার্সার তৈরি করতে পারে) | **স্টেটফুল** (বর্তমান উপাদান ও ইনডেক্স মনে রাখে) |
| **মূল মেম্বার** | \`IEnumerator<T> GetEnumerator()\` | \`bool MoveNext()\`, \`T Current { get; }\`, \`void Reset()\` |
| **বাস্তব উদাহরণ** | শেলফে রাখা একটি ছাপানো বই | বইয়ের ৪২ নম্বর পৃষ্ঠায় রাখা একটি ফিজিক্যাল বুকমার্ক |
| **কনকারেন্সি** | একাধিক থ্রেড একসাথে নিরাপদে রিড করতে পারে | একাধিক থ্রেডের মধ্যে শেয়ার করা মারাত্মক ঝুঁকিপূর্ণ |

---

## Foreach লুপের কম্পাইলার রূপান্তর (Compiler Lowering)

যখন আমরা C# এ একটি \`foreach\` লুপ লিখি, তখন কম্পাইলার (Roslyn) কোডটিকে একটি \`while\` লুপ এবং \`try-finally\` ব্লকে রূপান্তর করে:

\`\`\`csharp
// ডেভেলপার যে কোড লেখেন:
foreach (string city in cities)
{
    Console.WriteLine(city);
}
\`\`\`

কম্পাইলার ইন্টারনালি এটিকে এভাবে রূপান্তর করে:

\`\`\`csharp
// Roslyn কম্পাইলারের তৈরি রূপান্তর:
IEnumerator<string> enumerator = cities.GetEnumerator();
try
{
    while (enumerator.MoveNext())
    {
        string city = enumerator.Current;
        Console.WriteLine(city);
    }
}
finally
{
    // ফাইল স্ট্রিম বা আনম্যানেজড মেমোরি তাৎক্ষণিক ডিসপোজ নিশ্চিত করে
    if (enumerator != null)
    {
        enumerator.Dispose();
    }
}
\`\`\`

---

## প্যাটার্ন-ভিত্তিক ডাক টাইপিং (Duck Typing)

C# ল্যাঙ্গুয়েজের একটি অসাধারণ বৈশিষ্ট্য হলো, কোনো ক্লাসে \`foreach\` চালানোর জন্য ক্লাসটিকে **\`IEnumerable\` বা \`IEnumerator\` ইন্টারফেস ইমপ্লিমেন্ট করতেই হবে এমন কোনো বাধ্যবাধকতা নেই**!

C# কম্পাইলার **ডাক টাইপিং (Duck Typing)** প্যাটার্ন অনুসরণ করে। যদি কোনো ক্লাসে নিচের ৩টি বৈশিষ্ট্য থাকে, তবে \`foreach\` সফলভাবে কাজ করবে:
১. ক্লাসে একটি পাবলিক \`GetEnumerator()\` মেথড থাকতে হবে যা একটি অবজেক্ট বা স্ট্রাক্ট রিটার্ন করে।
২. রিটার্ন করা এনিউমারেটরে একটি পাবলিক \`bool MoveNext()\` মেথড থাকতে হবে।
৩. এনিউমারেটরে একটি পাবলিক \`Current\` রিড-অনলি প্রোপার্টি থাকতে হবে।

\`\`\`csharp
// কোনো ইন্টারফেস ছাড়াই foreach-এ কাজ করার উদাহরণ:
public class DuckSequence
{
    public DuckEnumerator GetEnumerator() => new DuckEnumerator();
}

public ref struct DuckEnumerator
{
    private int _count;
    public bool MoveNext() => ++_count <= 3;
    public int Current => _count;
}

// সফলভাবে কম্পাইল ও রান হবে:
foreach (int val in new DuckSequence())
{
    Console.WriteLine(val); // প্রিন্ট হবে: 1, 2, 3
}
\`\`\`

> **উচ্চ পারফরম্যান্সের সুবিধা**: আধুনিক .NET-এর \`Span<T>\` এবং \`ReadOnlySpan<T>\` এই ডাক টাইপিংয়ের ওপর ভিত্তি করে চলে। যেহেতু তারা \`ref struct\`, তাই তারা ইন্টারফেস ইমপ্লিমেন্ট করতে পারে না। ডাক টাইপিংয়ের কারণে তারা কোনো হিপ মেমোরি খরচ ছাড়াই \`foreach\` লুপে বিদ্যুৎ গতিতে চলতে পারে!

---

## স্ট্রাক্ট এনিউমারেটর ও বক্সিং পরিহার

\`List<T>\` এর মতো জনপ্রিয় কালেকশনের \`GetEnumerator()\` মেথড কোনো রেফারেন্স টাইপ রিটার্ন করে না, বরং একটি **মিউটেবল ভ্যালু-টাইপ স্ট্রাক্ট** (\`List<T>.Enumerator\`) রিটার্ন করে:

\`\`\`csharp
List<int> numbers = new() { 1, 2, 3 };

// জিরো অ্যালোকেশন: সরাসরি স্ট্যাকের ভেতর স্ট্রাক্ট এনিউমারেটর চলে
foreach (int n in numbers) { ... }

// মেমোরি লস: IEnumerable<int> এ কাস্ট করলে স্ট্রাক্টটি হিপে বক্সড (Boxed) হয়ে যায়!
IEnumerable<int> boxed = numbers;
foreach (int n in boxed) { ... }
\`\`\`

টাইট লুপে অপ্রয়োজনীয় গার্বেজ কালেকশন প্রেশার কমাতে কালেকশনকে ইন্টারফেসে কাস্ট করা পরিহার করা উচিত।

---

## বাস্তব সমস্যা সমাধান ও বিস্তারিত বিশ্লেষণ

### সমস্যা: Codeforces Assiut Sheet #3 Problem A (Summation)
*একটি সংখ্যা $N$ এবং $N$ আকারের একটি অ্যারে $A$ দেওয়া থাকবে। অ্যারের উপাদানগুলোর পরম যোগফল (Absolute Sum) বের করুন।*

#### সমাধান বিশ্লেষণ
১. ইনপুট সাইজ এবং সংখ্যা টোকেনগুলো রিড করা।
২. ৩২-বিট সীমানা ছাড়িয়ে যাওয়া আটকাতে ৬৪-বিট লং ইন্টিজারে যোগফল হিসাব করা।
৩. ম্যানুয়াল এনিউমারেটর ট্রাভার্সাল দিয়ে উপাদানগুলো একে একে পড়ে যোগ করা এবং \`Math.Abs\` দিয়ে পরম মান প্রিন্ট করা।

#### C# সমাধান

\`\`\`csharp
using System;
using System.Collections.Generic;

public class Program
{
    public static void Main()
    {
        string? nLine = Console.ReadLine();
        if (string.IsNullOrWhiteSpace(nLine)) return;

        string? arrayLine = Console.ReadLine();
        if (string.IsNullOrWhiteSpace(arrayLine)) return;

        string[] tokens = arrayLine.Trim().Split(' ', StringSplitOptions.RemoveEmptyEntries);

        long totalSum = 0;

        IEnumerator<string> enumerator = ((IEnumerable<string>)tokens).GetEnumerator();
        try
        {
            while (enumerator.MoveNext())
            {
                if (long.TryParse(enumerator.Current, out long value))
                {
                    totalSum += value;
                }
            }
        }
        finally
        {
            enumerator.Dispose();
        }

        long absoluteSum = Math.Abs(totalSum);
        Console.WriteLine(absoluteSum);
    }
}
\`\`\`

#### জটিলতা বিশ্লেষণ
- **টাইম কমপ্লেক্সিটি**: $\\mathcal{O}(N)$, $N$ সংখ্যক টোকেন একবার করে প্রসেস করে।
- **স্পেস কমপ্লেক্সিটি**: টোকেন সংরক্ষণে $\\mathcal{O}(N)$, এবং কার্সার নিয়ন্ত্রণে $\\mathcal{O}(1)$ মেমোরি।

---

## অনুশীলনের জন্য নির্বাচিত সমস্যা

| স্ট্যাটাস | সোর্স | সমস্যার নাম | কাঠিন্য | মূল ধারণা |
| :---: | :--- | :--- | :--- | :--- |
| ⚪ | Codeforces | [Assiut Sheet #3: Summation](https://codeforces.com/group/MWSDmqGsZm/contest/219774/problem/A) | Easy | Accumulator traversal, 64-bit summation |
| ⚪ | Codeforces | [Assiut Sheet #3: Searching](https://codeforces.com/group/MWSDmqGsZm/contest/219774/problem/B) | Easy | Linear scan, Early exit cursor |
| ⚪ | Exercism C# | [Strain](https://exercism.org/tracks/csharp/exercises/strain) | Medium | Custom collection enumeration, \`IEnumerator\` |
| ⚪ | Exercism C# | [Custom Set](https://exercism.org/tracks/csharp/exercises/custom-set) | Medium | Implementing \`IEnumerable<T>\` from scratch |
`,
  resources: [],
  problems: [
    {
      source: "Codeforces",
      name: "Assiut Sheet #3: Summation",
      url: "https://codeforces.com/group/MWSDmqGsZm/contest/219774/problem/A",
      difficulty: "EASY",
      company: "Brain Station 23",
      tags: ["Array", "Summation", "IEnumerator"],
      solutionEn:
        "Traverse the sequence of numbers using an enumerator loop and compute the 64-bit absolute sum.",
      solutionBn:
        "এনিউমারেটর লুপের সাহায্যে সংখ্যার সিকোয়েন্স ভিজিট করে ৬৪-বিট পরম যোগফল নির্ণয় করুন।",
    },
    {
      source: "Codeforces",
      name: "Assiut Sheet #3: Searching",
      url: "https://codeforces.com/group/MWSDmqGsZm/contest/219774/problem/B",
      difficulty: "EASY",
      company: "Therap Services",
      tags: ["Search", "Enumeration", "Array"],
      solutionEn:
        "Perform a linear scan across array elements to find the first zero-based index of target number X.",
      solutionBn:
        "অ্যারে উপাদানগুলোর মধ্যে লিনিয়ার সার্চ চালিয়ে টার্গেট সংখ্যা X এর প্রথম ইনডেক্স খুঁজে বের করুন।",
    },
    {
      source: "Exercism C#",
      name: "Strain",
      url: "https://exercism.org/tracks/csharp/exercises/strain",
      difficulty: "MEDIUM",
      company: "Enosis Solutions",
      tags: ["Generics", "Yield", "IEnumerator"],
      solutionEn:
        "Implement Keep and Discard operations over sequences by directly yielding filtered elements.",
      solutionBn:
        "ফিল্টার করা উপাদানগুলো ইল্ড করে সিকোয়েন্সের ওপর Keep ও Discard মেথড ইমপ্লিমেন্ট করুন।",
    },
    {
      source: "Exercism C#",
      name: "Custom Set",
      url: "https://exercism.org/tracks/csharp/exercises/custom-set",
      difficulty: "MEDIUM",
      company: "BJIT Group",
      tags: ["Collections", "IEnumerable", "Set"],
      solutionEn:
        "Build a custom mathematical set type that implements IEnumerable<T> with union, intersection, and difference.",
      solutionBn:
        "ইউনিয়ন, ইন্টারসেকশন ও ডিফারেন্স সমর্থনকারী একটি কাস্টম সেট টাইপ তৈরি করুন যা IEnumerable<T> ইমপ্লিমেন্ট করে।",
    },
  ],
};
